#!/usr/bin/env bash
# Build the monolithic main.js from source modules.
#
# Obsidian plugins are loaded as a single main.js file with no support for
# relative requires.  The source modules under src/ are self-contained and
# this script concatenates them in dependency order so that every symbol is
# defined before it is referenced.
#
# Usage:
#   bash build.sh

set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
SRC="$DIR/src"
OUT="${OUT:-$DIR/main.js}"

{
  cat <<'HEADER'
// ========================================================================
// Auto-generated by build.sh — do not edit directly.
// Source modules live under src/. Run 'bash build.sh' to regenerate.
// ========================================================================

const { Plugin, PluginSettingTab, Setting, ItemView, Modal, Notice } = require("obsidian");
const { spawn } = require("child_process");
const fs = require("fs");
const path = require("path");
let electron = null;
try {
  electron = require("electron");
} catch (error) {
  electron = null;
}
const clipboard = electron && electron.clipboard ? electron.clipboard : null;
const shell = electron && electron.shell ? electron.shell : null;

HEADER

  first_module=1
  for module in llm_settings constants helpers command_specs pending_state pending_runtime context_state today_feed modals views state/repo-state bridge/launcher bridge/runtime_client render/cards settings render_primitives render_input render_today render_advanced render_home plugin_helpers rewrite_state control_items modal_specs run_state run_log_persistence plugin_state curated_view plugin_lifecycle plugin_actions plugin_run_pipeline state/health-state plugin; do
    if [[ "$first_module" -eq 0 ]]; then
      echo ""
    fi
    first_module=0
    echo "// --- src/${module}.js ---"
    echo ""
    cat "$SRC/${module}.js"
  done
} > "$OUT"

echo "Built $OUT ($(wc -l < "$OUT") lines)"
