#!/usr/bin/env bash
# Build the monolithic main.js from source modules.
#
# Obsidian plugins are loaded as a single main.js file with no support for
# relative requires.  The source modules under src/ are self-contained and
# this script concatenates them in dependency order so that every symbol is
# defined before it is referenced.
#
# Usage:
#   bash build.sh

set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
SRC="$DIR/src"
OUT="$DIR/main.js"

{
  cat <<'HEADER'
// ========================================================================
// Auto-generated by build.sh — do not edit directly.
// Source modules live under src/. Run 'bash build.sh' to regenerate.
// ========================================================================

const { Plugin, PluginSettingTab, Setting, ItemView, Modal, Notice } = require("obsidian");
const { spawn } = require("child_process");
const fs = require("fs");
const path = require("path");

HEADER

  for module in constants helpers modals views settings render plugin; do
    echo "// --- src/${module}.js ---"
    echo ""
    cat "$SRC/${module}.js"
    echo ""
  done
} > "$OUT"

echo "Built $OUT ($(wc -l < "$OUT") lines)"
