// Constants, default settings, i18n dictionary, and status label maps.

const PLUGIN_ID = "furnace-product-shell";
const VIEW_TYPE_FURNACE_CENTER = "furnace-product-shell-furnace-center";
const SHELL_SUMMARY_PATH = "output/control/shell-summary.json";
const DEFAULT_PROTOCOLS = ["general"];
const DEFAULT_LOCALE = "zh";
const DEFAULT_SETTINGS = {
  launcherPath: "scripts/aiwiki-launcher.sh",
  runtimeClientMode: "desktop-launcher",
  defaultAskFormat: "report",
  recentRunsLimit: 8,
  showAdvancedCommands: false,
  locale: DEFAULT_LOCALE,
  llmBackend: "opencode-api",
  llmModel: "deepseek-v4-pro",
  llmDeepseekApiKey: "",
  llmDeepseekBaseUrl: "",
  llmOpencodeApiKey: "",
  llmOpencodeBaseUrl: "",
  llmAnthropicApiKey: "",
  llmAnthropicBaseUrl: "",
  llmCustomOpenaiApiKey: "",
  llmCustomOpenaiBaseUrl: "",
  feishuWebhookUrl: "",
  wecomWebhookUrl: "",
  enabledChannels: [],
  lastViewedTimestamp: "",
  lastKnownReportIds: [],
  onboardingShown: false,
  // R91: Advanced 子 section 折叠态持久化；默认全折叠以降首屏认知负担
  advancedSectionsExpanded: { status: false, history: false },
};
const ZH_TEXT = {
  "Advanced": "更多工具",
  "Furnace Product Shell": "炼丹炉 Product Shell",
  "UI language": "界面语言",
  "Default display language for the Product Shell UI. Command palette labels refresh after reloading Obsidian.": "Product Shell 默认显示语言。修改后，命令面板标签需要重载 Obsidian 才会刷新。",
  Chinese: "中文",
  English: "英文",
  "Aiwiki launcher": "Aiwiki 启动器",
  "Vault-local or absolute launcher path. This vault may point at an external runtime root.": "vault 内相对路径或绝对 launcher 路径。这个 vault 可以指向外部 runtime root。",
  "Runtime client mode": "运行客户端模式",
  "Desktop launcher runs the local aiwiki runtime. Vault queue only writes .aiwiki/queue requests for desktop drain; it does not execute commands.": "Desktop launcher 会运行本机 aiwiki runtime。Vault queue 只写入 .aiwiki/queue 请求等待桌面端 drain，不执行命令。",
  "Desktop launcher": "桌面启动器",
  "Vault queue companion": "Vault 队列 companion",
  "Recent runs limit": "最近运行保留数",
  "How many plugin-triggered runs to keep in the Product Shell.": "Product Shell 中保留多少条插件触发的运行记录。",
  "Show advanced commands": "显示高级命令",
  "Register the Refresh Furnace Shell command in the command palette. Reload Obsidian after changing this toggle.": "是否把「刷新炼丹炉 Shell」命令注册到命令面板中。修改后需要重载 Obsidian。",
  "Advanced command visibility refreshes after reloading Obsidian.": "高级命令可见性会在重载 Obsidian 后刷新。",
  "Recent plugin-triggered runs are listed here when available.": "此处列出插件触发的最近运行记录（如有）。",
  "Full runtime is Desktop-only. iPad/iOS Obsidian can only be a future companion; it cannot run the local launcher, Python CLI, or full ingest/review flow.": "全功能 runtime 仅支持 Desktop。iPad/iOS Obsidian 未来只能作为 companion，不能运行本地 launcher、Python CLI 或完整投料/复审流程。",
  "LLM backend": "LLM 后端",
  "Select the LLM provider used by compile / run-ask / run-nightly. Common providers are listed first; advanced entries are for local CLI sessions or custom OpenAI-compatible endpoints.": "选择 compile / run-ask / run-nightly 使用的 LLM API provider。",
  "LLM model": "LLM 模型",
  "Model for the selected API provider. Empty uses that provider profile default when one exists.": "所选 API provider 的模型。留空时使用该 provider profile 的默认模型（如果有）。",
  "API key": "API Key",
  "Stored only in local Obsidian plugin data. New runs use the key saved here and ignore stale LLM environment variables.": "仅存放在本机 Obsidian 插件数据中。新的运行会使用这里保存的 key，并忽略旧的 LLM 环境变量。",
  "Base URL": "Base URL",
  "Override the provider endpoint. Leave empty to use the provider profile default.": "覆盖 provider endpoint。留空则使用 provider profile 默认值。",
  "CLI session": "CLI 会话",
  "This backend uses a local CLI login/session. API key fields are not used.": "该后端已不再作为 Product Shell 后端使用。",
  "LLM settings saved. New runs will use the updated configuration.": "LLM 设置已保存。新的运行将使用更新后的配置。",
  "Notifications (webhook)": "通知（webhook）",
  "Webhook settings are stored only in local plugin data. Failures are not retried. Notifications are only for new reports.": "Webhook 设置仅保存在本地插件数据中。失败不会重试。通知只用于新报告。",
  "Feishu webhook URL": "飞书 webhook URL",
  "WeCom webhook URL": "企业微信 webhook URL",
  "Enable Feishu": "启用飞书",
  "Enable WeCom": "启用企业微信",
  "Universal input": "统一输入",
  "Universal Input": "统一输入",
  "Universal input cannot be empty.": "统一输入不能为空。",
  "Ctrl+Enter 提交 · 也可拖入文件": "Ctrl+Enter 提交 · 也可拖入文件",
  "Drop file here": "把文件拖到这里",
  Submit: "提交",
  "Invalid input: {message}": "输入无效：{message}",
  Question: "问题",
  Format: "格式",
  Mode: "模式",
  Protocol: "协议",
  "current protocol": "当前协议",
  Run: "运行",
  Cancel: "取消",
  "Nothing to copy.": "没有可复制的内容。",
  "Clipboard is not available in this environment.": "当前环境不支持剪贴板。",
  "Copied to clipboard.": "已复制到剪贴板。",
  "LLM health": "LLM 状态",
  Sync: "同步",
  "Configured route": "当前模型",
  "Last checked": "最近检测",
  "Refreshing shell summary.": "正在刷新数据。",
  "Latest refresh failed.": "最近一次刷新失败。",
  "Summary ready.": "数据已就绪。",
  "No recent LLM health check yet.": "还没有最近一次 LLM 状态检查。",
  "LLM is not configured.": "当前没有配置 LLM。",
  "Current route changed since the last recorded ask.": "当前路由已经和最近一次记录的 Ask 不同。",
  degraded: "降级",
  warning: "警告",
  "Recent run-ask succeeded.": "最近一次 run-ask 成功完成。",
  "Latest run-ask succeeded.": "最近一次 run-ask 成功完成。",
  "Recent run-ask fell back to deterministic scaffold (legacy receipt).": "最近一次 run-ask 命中历史 deterministic-fallback receipt（路径已退役）。",
  "Latest run-ask produced an LLM failure notice.": "最近一次 run-ask 生成了 LLM 失败说明。",
  "LLM timed out or failed before producing an answer.": "LLM 超时或失败，未产出答案。",
  "LLM timed out or failed. Open the failure notice for details, then retry or switch model.": "LLM 超时或失败。可打开失败说明查看细节，再重试或切换模型。",
  "LLM timed out; no substantive answer was generated. Try again or switch model.": "LLM 超时，未生成实质回答。请重试或切换模型。",
  "Latest run-ask failed before producing an LLM result.": "最近一次 run-ask 在生成 LLM 结果前失败。",
  available: "可用",
  "configured but unavailable": "已配置但不可用",
  "not configured": "未配置",
  "No backup LLM route configured.": "未配置备用 LLM 路由。",
  "Backup LLM route ready: {count}/{total}": "备用 LLM 路由就绪：{count}/{total}",
  "Backup LLM route not ready.": "备用 LLM 路由未就绪。",
  "已有进行中的提问，请等待完成后再试。": "已有进行中的提问，请等待完成后再试。",
  "正在生成": "正在生成",
  "仍在生成，请稍候": "仍在生成，请稍候",
  "Latest run-ask failed without deterministic fallback.": "最近一次 run-ask 失败，且没有进入 deterministic fallback。",
  "LLM failure notice active": "LLM 失败说明已启用",
  "No Product Shell ask has been recorded yet.": "当前还没有 Product Shell Ask 记录。",
  "Product Shell ask history matches the current route.": "Product Shell 的 Ask 历史与当前路由一致。",
  "Latest Product Shell ask used {latest}; current route is {current}.": "最近一次 Product Shell Ask 使用的是 {latest}；当前路由是 {current}。",
  "requested {requested} · effective {effective} · available {available}": "请求 {requested} · 生效 {effective} · 可见 {available}",
  "No explicit LLM backend is selected. Choose one in Product Shell settings or set AIWIKI_LLM_BACKEND.": "当前没有显式选择 LLM 后端。请在 Product Shell 设置里选择，或设置 AIWIKI_LLM_BACKEND。",
  "Product Shell runtime can see the selected backend {backend}.": "Product Shell 当前 runtime 能看到所选后端 {backend}。",
  "Product Shell runtime cannot see the selected backend {backend}.": "Product Shell 当前 runtime 看不到所选后端 {backend}。",
  "Summary is stale; refresh before trusting the home surface.": "数据已过期，先刷新，再相信首页状态。",
  "Generated {time}": "生成于 {time}",
  "launcher {launcher} · root {root}": "launcher {launcher} · 根目录 {root}",
  Fallback: "回退",
  "Capture Material": "投文字材料",
  "欢迎使用炼丹炉": "欢迎使用炼丹炉",
  投料: "投料",
  "拖入 URL、PDF 或图片，或直接在输入框提问": "拖入 URL、PDF、Markdown 或图片，或直接在输入框提问",
  等待编译: "等待编译",
  "炉子会自动处理原料，抽概念、建关联": "炉子会自动处理原料，抽概念、建关联",
  看报告: "看报告",
  "每天回到炉子，Today 里就是你需要看的": "每天回到炉子，Today 里就是你需要看的",
  "知道了，开始使用": "知道了，开始使用",
  "新反证待审": "新反证待审",
  "判断需要复核": "判断需要复核",
  "机器记忆待修复": "机器记忆待修复",
  "待定判断": "待定判断",
  "待定决策": "待定决策",
  "安全动作待确认": "安全动作待确认",
  "升级动作": "升级动作",
  "升级候选": "升级候选",
  "逾期动作": "逾期动作",
  "逾期复审": "逾期复审",
  "数据漂移": "数据漂移",
  "待审队列": "待审队列",
  "指标提醒": "指标提醒",
  新报告: "新报告",
  自动维护: "自动维护",
  "系统动态": "系统动态",
  "金丹完成": "金丹完成",
  "待确认操作": "待确认操作",
  正常运行: "正常运行",
  待确认: "待确认",
  需要关注: "需要关注",
  空闲: "空闲",
  "Language & Appearance": "语言与外观",
  "Furnace Connection": "炉子连接",
  "Ask Defaults": "Ask 默认行为",
  "LLM Configuration": "LLM 配置",
  Notifications: "通知",
  "刷新炉子": "刷新炉子",
  "搜索知识库": "搜索知识库",
  "搜索 wiki、概念、判断、决策和派生页面。": "搜索 wiki、概念、判断、决策和派生页面。",
  "关键词": "关键词",
  "输入关键词搜索……": "输入关键词搜索……",
  "搜索关键词不能为空。": "搜索关键词不能为空。",
  "搜索中…": "搜索中…",
  "搜索": "搜索",
  "来源": "来源",
  "结果数量": "结果数量",
  Title: "标题",
  Kind: "类型",
  Text: "正文",
  "This writes into raw/inbox through the same launcher/runtime used by CLI commands.": "这会通过与 CLI 相同的 launcher/runtime 写入 raw/inbox。",
  Capture: "记录",
  "Text cannot be empty.": "正文不能为空。",
  "Set Protocol": "设置协议",
  Apply: "应用",
  "Choose a protocol.": "请选择协议。",
  "Set protocol modal": "设置协议模态框",
  "Search 炼丹炉": "搜索炼丹炉",
  Query: "查询",
  "Search wiki/sources, concepts, judgments, decisions, and derived pages...": "搜索 wiki/sources、concepts、judgments、decisions 和 derived 页面……",
  Limit: "数量上限",
  Search: "搜索",
  "Search query cannot be empty.": "搜索词不能为空。",
  "Search modal": "搜索模态框",
  "Run command": "运行命令",
  "Pick context": "选择上下文",
  Close: "关闭",
  Use: "使用",
  "command modal": "命令模态框",
  "context picker": "上下文选择器",
  "{field} cannot be empty.": "{field} 不能为空。",
  "No context is currently available.": "当前没有可用上下文。",
  "No context is currently available; fell back to the manual form.": "当前没有可用上下文，已回退到手动表单。",
  "Open Furnace Center": "打开炉心面板",
  "Open Furnace": "打开炼丹炉",
  "Refresh Furnace Shell": "刷新炼丹炉 Shell",
  Compile: "编译",
  Ask: "提问",
  "Drop URL": "投网址",
  "Drop File": "投文件",
  "Drop Image": "投图片",
  "Drop Material": "投料",
  "Search Workspace": "搜索工作区",
  Nightly: "夜间巡检",
  "File Back": "回流归档",
  "Review Page": "审阅页面",
  "Review Next Page": "审阅下一页",
  "Review Rewrite": "审阅改写",
  "rewrite proposals: {count}": "改写提案：{count}",
  "Apply Rewrite": "应用改写",
  "Retire Concept": "退役概念",
  "Reactivate Concept": "重新激活概念",
  "Review Action": "审阅动作",
  "Apply Action": "应用动作",
  "Revert Action": "回滚动作",
  "Apply All Accepted Low-Risk Actions": "应用所有已接受的低风险动作",
  "Revert Last Action Batch": "回滚上一批动作",
  "Open Home Note": "打开首页笔记",
  Home: "首页",
  Refresh: "刷新",
  "Start Here": "从这里开始",
  "Click Refresh first so shell-summary is generated.": "先点刷新生成最新数据。",
  "先点刷新生成最新数据。": "先点刷新生成最新数据。",
  "Follow single writer for write actions: do not run compile / nightly / apply / revert in Obsidian and the terminal at the same time.": "有写入任务运行时，等它结束后再从另一个入口开始新的写入任务。",
  "Vault runtime unavailable. Missing scaffold or launcher: {missing}": "Vault runtime 不可用。缺少 scaffold 或 launcher：{missing}",
  "Expected a vault scaffold (`raw/wiki/schema/output/.aiwiki`) plus an executable launcher script.": "预期存在 vault scaffold（`raw/wiki/schema/output/.aiwiki`）以及可执行的 launcher 脚本。",
  "shell-summary.json has not been generated yet. Run Refresh, Compile, or Nightly first.": "数据还没生成。先点刷新，或等首次任务跑完。",
  "数据还没生成。先点刷新，或等首次任务跑完。": "数据还没生成。先点刷新，或等首次任务跑完。",
  "Active Protocol": "当前协议",
  "LLM Backend": "LLM 服务",
  "LLM Model": "LLM 模型",
  "Codex effort": "Codex 档位",
  "Prompt profile": "Prompt 档位",
  "Retry prompt": "重试 Prompt",
  "codex effort {value}": "Codex 档位 {value}",
  "prompt {value}": "Prompt 档位 {value}",
  "retry {value}": "重试 Prompt {value}",
  "Usage Visibility": "Usage 可见性",
  "Pending Reviews": "待审阅",
  Overdue: "逾期",
  Escalation: "升级候选",
  "System status": "运行状态",
  "Status checks": "状态检查",
  "Self-check": "自我检查",
  "Make sure frontend state and runtime state still agree.": "确认前端状态和 runtime 状态仍然对应一致。",
  "Runtime contract": "运行时契约",
  "Shell summary": "Shell 摘要",
  "LLM route": "LLM 路由",
  "Backend discovery": "后端发现",
  "Latest ask execution": "最近一次 Ask 执行",
  "Route drift": "路由漂移",
  "Make runtime state explicit before you act.": "先确认当前没有冲突中的写入任务。",
  Ready: "就绪",
  "No command is currently running.": "当前没有任务在运行。",
  "{count} command(s) running right now.": "当前有 {count} 个任务正在运行。",
  "Single writer active: avoid compile / nightly / apply / revert from two surfaces at once.": "已有写入任务在运行；等它结束后再开始新的写入任务。",
  Summary: "摘要",
  "Generated at {generated_at} | contract v{version}": "生成于 {generated_at} | contract v{version}",
  "Knowledge Base": "知识库",
  Sources: "来源",
  Concepts: "概念",
  Judgments: "判断",
  Decisions: "决策",
  Edges: "边",
  "Causal Edges": "因果边",
  "Term Index": "术语索引",
  Dashboard: "仪表盘",
  "⚠️ Drift Warnings": "⚠️ 漂移警告",
  Today: "今天",
  "Furnace activity": "炉子动态",
  "No recent furnace activity": "暂无炉子动态",
  "Plugin run": "插件运行",
  Receipt: "回执",
  "Review backlog": "待处理积压",
  "需要你确认": "需要你确认",
  "下一步建议": "下一步建议",
  "(nothing for today)": "今天暂无待处理内容",
  "Needs Decision": "需要判断",
  Proposals: "提案",
  Completed: "已完成",
  "Suggested Actions": "建议动作",
  // R89: pending 状态文案
  "处理中…": "处理中…",
  "已收料": "已收料",
  "正在收料": "正在收料",
  "投料失败": "投料失败",
  "已存在，未重复入库": "已存在，未重复入库",
  "投 URL / PDF / Markdown / 图片 / repo；提问才会生成报告": "投 URL / PDF / Markdown / 图片 / repo；提问才会生成报告",
  "Ctrl+Enter 提交 · 拖入文件 · 投料入 raw，提问出报告": "Ctrl+Enter 提交 · 拖入文件 · 投料入 raw，提问出报告",
  "报告已生成": "报告已生成",
  // R90: 提交→状态→结果 闭环
  "查看回执": "查看回执",
  "完成": "完成",
  "未刷新": "未刷新",
  "刚刚": "刚刚",
  "已打开输出汇总（找不到具体报告路径）": "已打开输出汇总（找不到具体报告路径）",
  "已回到 Today（找不到具体回执路径）": "已回到 Today（找不到具体回执路径）",
  "无法打开目标，可能尚未生成": "无法打开目标，可能尚未生成",
  // R91 Advanced 抽屉子 section
  "系统状态": "系统状态",
  "运行与历史": "运行与历史",
  "以下为运行诊断与历史": "以下为运行诊断与历史",
  "运行诊断 · 同步 {sync}": "运行诊断 · 同步 {sync}",
  "最近运行 {n} 条 · 待审 {review}": "最近运行 {n} 条 · 待审 {review}",
  "未配置": "未配置",
  "正常": "正常",
  "异常": "异常",
  "未知": "未知",
  "点击展开查看详细信息": "点击展开查看详细信息",
  "{n} 分钟前": "{n} 分钟前",
  "{n} 小时前": "{n} 小时前",
  "{n} 天前": "{n} 天前",
  "失败": "失败",
  "重试": "重试",
  Dismiss: "关闭",
  "这次没成功。可以点重试，或检查输入是否完整。": "这次没成功。可以点重试，或检查输入是否完整。",
  // R89: Advanced 抽屉开发者分隔
  "以下为开发者诊断信息": "以下为开发者诊断信息",
  "reason {value}": "原因 {value}",
  Open: "打开",
  "Open report": "打开报告",
  "View report graph": "查看报告关系图谱",
  "View graph": "查看关系图谱",
  "Open evidence graph": "打开证据关系图",
  "Evidence graph": "证据关系图",
  "Report path cannot be empty.": "报告路径不能为空。",
  "Enter a report markdown path (relative to vault root).": "请输入 report markdown 路径（相对 vault 根目录）。",
  "Report path": "报告路径",
  "No recent reports available; enter a path manually.": "暂无最近报告，可手动输入路径。",
  "Choose a recent report.": "选择最近报告。",
  "Open decision": "打开决策",
  "Open judgment": "打开判断",
  "Copy target": "复制目标",
  Report: "报告",
  "Decision page": "决策页",
  "Judgment page": "判断页",
  "Proposal page": "提案页",
  "Graph page": "关系图谱",
  "Review surface": "审阅入口",
  "Workspace page": "工作区页面",
  "Metric alert": "指标提醒",
  "Command prepared for manual confirmation": "命令已准备，复制后人工确认",
  "Search Results": "搜索结果",
  "Recent Queries": "最近查询",
  "Judgment Focus": "判断焦点",
  "Quick Links": "快捷链接",
  More: "更多",
  none: "无",
  Review: "审阅",
  "Next Action": "下一动作",
  "Open page": "打开页面",
  "Open first": "打开第一项",
  "Open proposal": "打开提案",
  "Open target": "打开目标",
  "Open primary": "打开主路径",
  "Open receipt": "打开回执",
  "Open result": "打开结果",
  "Copy result path": "复制结果路径",
  "Apply action": "应用动作",
  "Revert action": "回滚动作",
  "Apply archive": "应用归档",
  "Revert archive": "回滚归档",
  "Reactivate concept": "重新激活概念",
  "Review action": "审阅动作",
  "Furnace": "炼丹炉",
  "Furnace Center": "炉心面板",
  "Furnace shell unavailable": "炼丹炉 shell 不可用",
  "Missing runtime paths: {missing}": "缺少运行时路径：{missing}",
  "Furnace Product Shell active protocol {protocol}": "炼丹炉 Product Shell 当前协议 {protocol}",
  " | syncing": " | 同步中",
  " | running {count}": " | 运行中 {count}",
  "Command failed with exit code {code}": "命令失败，退出码 {code}",
  "unknown error": "未知错误",
  "No plugin-triggered commands yet.": "当前还没有插件触发的命令。",
  "No recent outputs are available.": "当前没有 recent outputs。",
  "shell-summary.json is not available yet. Run Refresh, Compile, or Nightly first.": "数据还没准备好。先点上方刷新，或等当前任务跑完。",
  "数据还没准备好。先点上方刷新，或等当前任务跑完。": "数据还没准备好。先点上方刷新，或等当前任务跑完。",
  "数据还没就绪。先点上方刷新，或等首次任务跑完。": "数据还没就绪。先点上方刷新，或等首次任务跑完。",
  "Repo-local runtime unavailable. Missing: {missing}": "Repo-local runtime 不可用。缺少：{missing}",
  "No visible review backlog item is available; fell back to the manual form.": "当前没有可见的 review backlog 条目，已回退到手动表单。",
  "No reviewable page is available.": "当前没有可 review 的页面。",
  "No visible concept context is available; fell back to the manual form.": "当前没有可见的 concept context，已回退到手动表单。",
  "No visible machine-memory action context is available; fell back to the manual form.": "当前没有可见的 machine-memory action context，已回退到手动表单。",
  "No visible archive context is available; fell back to the manual form.": "当前没有可见的 archive context，已回退到手动表单。",
  "No explicit review transition is available; fell back to the manual form.": "当前没有显式 review transition，已回退到手动表单。",
  "No explicit rewrite transition is available; fell back to the manual form.": "当前没有显式 rewrite transition，已回退到手动表单。",
  "No explicit action transition is available; fell back to the manual form.": "当前没有显式 action transition，已回退到手动表单。",
  "priority": "优先级",
  "score": "分数",
  "review object": "审阅对象",
  "review-object": "审阅对象",
  "judgment asset": "判断资产",
  "Artifact path": "产物路径",
  "Page path": "页面路径",
  "Page paths": "页面路径",
  "Concept slug": "概念 slug",
  "Entry id": "条目 id",
  "Action id": "动作 id",
  "Bundle path": "bundle 路径",
  "Status": "状态",
  "Note": "备注",
  "Confidence": "置信度",
  "Dry run": "仅演练",
  "output/reports/....md": "output/reports/....md",
  "Optional filed-back title": "可选回填标题",
  "wiki/decisions/... or wiki/judgments/...": "wiki/decisions/... 或 wiki/judgments/...",
  "confirmed / discarded / pending-review": "confirmed / discarded / pending-review",
  "approved / confirmed / needs-revision ...": "approved / confirmed / needs-revision ...",
  "accepted / rejected / needs-revision ...": "accepted / rejected / needs-revision ...",
  "accepted / rejected / ready ...": "accepted / rejected / ready ...",
  "Optional review note": "可选审阅备注",
  "Optional action review note": "可选动作审阅备注",
  "Optional confidence override": "可选置信度覆盖",
  "Optional apply note": "可选应用备注",
  "Optional revert note": "可选回滚备注",
  "Optional reactivate note": "可选重新激活备注",
  "Optional shared batch note": "可选批量共享备注",
  "Optional shared confidence override": "可选共享置信度覆盖",
  "Optional execution bundle path": "可选执行 bundle 路径",
  "Why retire this concept?": "为什么要退役这个概念？",
  "machine-memory action id": "machine-memory 动作 id",
  "manifest/material entry id": "manifest/material 条目 id",
  "wiki/judgments/... (one per line)": "wiki/judgments/...（每行一个）",
  "tracking / needs-revisit / approved ...": "tracking / needs-revisit / approved ...",
  "Run batch": "运行批量操作",
  "Pick Review Page": "选择审阅页面",
  "Pick Rewrite Context": "选择改写上下文",
  "Pick Review Action": "选择审阅动作",
  "Pick Archive Target": "选择归档目标",
  "Pick Archive Revert Target": "选择归档回滚目标",
  "Pick Apply Action": "选择应用动作",
  "Pick Revert Action": "选择回滚动作",
  "Pick Review Transition": "选择审阅迁移",
  "Pick Rewrite Transition": "选择改写迁移",
  "Pick Action Transition": "选择动作迁移",
  "Advance a decision or judgment page through the explicit review workflow.": "通过显式审阅流程推进决策或判断页面。",
  "Advance a concept rewrite proposal through the rewrite workflow.": "通过改写流程推进概念改写提案。",
  "Apply an accepted concept rewrite proposal.": "应用一个已接受的概念改写提案。",
  "Apply an explicit retired override for a concept.": "为概念应用显式 retired 覆盖。",
  "Clear the explicit retired override for a concept.": "清除概念上的显式 retired 覆盖。",
  "Apply a ready archive candidate and pin it to archived.": "应用一个已准备好的归档候选，并将其固定为 archived。",
  "Revert the latest explicit archive transition.": "回滚最近一次显式归档迁移。",
  "Advance a machine-memory repair action through the explicit action workflow.": "通过显式动作流程推进 machine-memory 修复动作。",
  "Apply an accepted low-risk machine-memory repair action.": "应用一个已接受的低风险 machine-memory 修复动作。",
  "Revert the latest low-risk safe apply for a machine-memory action.": "回滚 machine-memory 动作最近一次低风险安全应用。",
  "File an output artifact back into wiki/judgments for thin review.": "将输出报告回填到 wiki/judgments，进入薄审阅流程。",
  "Prefer an explicit review control object before falling back to manual page entry.": "优先使用显式 review control object，再回退到手动输入页面。",
  "Advance multiple review pages that share a safe common transition.": "批量推进共享安全公共迁移的多个审阅页面。",
  "Prefer an explicit rewrite proposal object before falling back to manual slug entry.": "优先使用显式 rewrite proposal object，再回退到手动输入 slug。",
  "Prefer an explicit action control object before falling back to manual action id entry.": "优先使用显式 action control object，再回退到手动输入 action id。",
  "Prefer an explicit archive control object before falling back to manual entry id.": "优先使用显式 archive control object，再回退到手动输入 entry id。",
  "Choose a valid next status for this review page.": "为这个审阅页面选择一个有效的下一状态。",
  "Choose a valid next status for this rewrite proposal.": "为这个改写提案选择一个有效的下一状态。",
  "Choose a valid next status for this machine-memory action.": "为这个 machine-memory 动作选择一个有效的下一状态。",
  "share the recommended transition": "共享推荐迁移",
  "actions": "动作",
  "archives": "归档",
  "decision_pages": "决策页面",
  "judgment_pages": "判断页面",
  "rewrite_proposals": "改写提案",
  "derived": "派生产物",
  "Apply Archive": "应用归档",
  "Revert Archive": "回滚归档",
  "Apply rewrite": "应用改写",
  "result-usage": "返回 usage",
  "response-usage": "返回 usage",
  "opaque-cli": "CLI 不透明",
  unconfigured: "未配置",
  unknown: "未知",
  success: "成功",
  running: "运行中",
  failed: "失败",
  default: "默认",
  medium: "中",
  operation: "操作",
  event: "事件",
  results: "结果数",
  query: "查询",
  result: "结果",
  output: "输出",
  receipt: "回执",
  review: "审阅",
  action: "动作",
  context: "上下文",
  command: "命令",
  transition: "迁移",
  card: "卡片",
  drift: "漂移",
  "review-page": "审阅页面",
  "rewrite-proposal": "改写提案",
  "archive-entry": "归档条目",
  "judgment-asset": "判断资产",
  "runtime-event": "运行事件",
  apply: "应用",
  revert: "回滚",
  "file-back": "回流归档",
  "alchemy-start": "凝丹启动",
  "archive-apply": "归档应用",
  "archive-revert": "归档回滚",
  "knowledge-lifecycle-override": "生命周期覆盖",
  general: "通用",
  source: "来源",
  concept: "概念",
  markdown: "Markdown",
  html: "HTML",
  json: "JSON",
  proposed: "提议",
  approved: "已批准",
  "needs revisit": "需回看",
  superseded: "已替代",
  tentative: "暂定",
  tracking: "跟踪中",
  confirmed: "已确认",
  rejected: "已拒绝",
  accepted: "已接受",
  deferred: "已延期",
  resolved: "已解决",
  applied: "已应用",
  "pending review": "待审阅",
  "overdue review": "逾期审阅",
  "escalation candidate": "升级候选",
  "scheduled review": "计划审阅",
  "missing counter evidence": "缺少反证",
  "missing invalidation": "缺少失效条件",
  "missing next signals": "缺少下一信号",
  "missing review history": "缺少审阅历史",
  "citation drift": "引用漂移",
  "citation snapshot gap": "引用快照缺口",
  "confidence {value}": "置信度 {value}",
  "asset {value}/4": "资产分 {value}/4",
  "history {value}": "历史 {value}",
  "drift {value}": "漂移 {value}",
  "snapshot gaps {value}": "快照缺口 {value}",
  "preferred transition": "推荐迁移",
  "allowed transition": "允许迁移",
  "Manual review...": "手动审阅……",
  "Manual rewrite review...": "手动改写审阅……",
  "Manual action review...": "手动动作审阅……",
  "keep current status and capture note / confidence in the full form": "保留当前状态，并在完整表单里填写 note / confidence",
  "Search completed: {query}": "搜索完成：{query}",
  "Cannot parse command: {command}": "无法解析命令：{command}",
  "No path to open.": "没有可打开的路径。",
  "Unable to open {path}": "无法打开 {path}",
  "Path not found: {path}": "路径不存在：{path}",
  "Unable to open resource: {path}": "无法打开资源：{path}",
  "File exists but Obsidian has not indexed it (check Excluded files / userIgnoreFilters): {path}":
    "文件存在但 Obsidian 未索引（请检查「排除的文件」/ userIgnoreFilters）：{path}",
  Materials: "原料投入",
  "Push new material into the furnace.": "把新原料投进炉子，等下一次编译或夜间巡检收敛。",
  "Latest outputs": "最新产出",
  "Open the newest outputs without diving into control surfaces.": "直接打开最新产出，不必先进入复杂控制面板。",
  "View all": "查看全部",
  "No recent outputs yet. Drop material or run a compile.": "还没有最新产出；先投料或运行一次编译。",
  "Daily Digest": "今日简报",
  "A compact pulse for knowledge, review, and nightly health.": "用一张卡片看知识库、审阅和例行检查状态。",
  "Last sync": "最后同步",
  "Summary unavailable. The panel will sync automatically when possible.": "当前还没有 summary；面板会在可用时自动同步。",
  "Advanced Actions": "工具操作",
  "Core workflows stay available here, but hidden by default.": "核心工作流仍然都在，只是默认折叠起来。",
  "Knowledge Compounding Metrics": "知识复利指标",
  "(metrics unavailable; run aiwiki metrics for details)": "指标暂不可用；需要详情时打开指标报告。",
  "Provenance Completeness": "来源完整度",
  "Stale Page Ratio": "过期页面占比",
  "Review Closure Rate (7d)": "审阅完成率（7 天）",
  "Proposal Acceptance Rate": "提案采纳率",
  "Judgment Revisit Rate": "判断复核率",
  "Output File-back Rate": "产出回填率",
  "Elixir Reuse Count": "复用沉淀数",
  "Run `aiwiki metrics --json` for full data.": "完整指标数据可在指标报告中查看。",
  "Latest plugin runs": "最近运行",
  "Latest run": "最近一次运行",
  "No recent plugin runs.": "当前还没有插件运行记录。",
  "Open log": "打开日志",
  "Copy command": "复制命令",
  "Reveal result": "定位结果",
  "Reveal receipt": "定位回执",
  "Copy receipt path": "复制运行记录路径",
  "Copy stderr": "复制错误输出",
  "Unable to reveal {path}": "无法定位 {path}",
  "Path revealed: {path}": "已定位 {path}",
  "Path not found: {path}": "路径不存在：{path}",
  "No stage events recorded.": "当前没有记录到阶段事件。",
  Submitted: "已提交",
  "Runtime selected": "运行上下文",
  Executing: "执行中",
  Completed: "已完成",
  Failed: "失败",
  Artifacts: "产物",
  "Sync now": "立即同步",
  "backend {value}": "后端 {value}",
  "model {value}": "模型 {value}",
  selected: "初始",
  final: "最终",
  "fallback {value}": "回退 {value}",
  "protocol {value}": "协议 {value}",
  "Re-run": "重新运行",
  " | llm degraded": " | LLM 已降级",
  "Cannot re-run this entry because argv was not recorded.": "这条记录没有保存 argv，暂时无法重新运行。",
  "Command completed successfully.": "命令已成功完成。",
  "Queued for desktop drain: {path}": "已加入桌面端待处理队列：{path}",
  "Queued for desktop drain. This is not a completed runtime execution.": "已加入桌面端待处理队列。这不是已完成的 runtime 执行。",
  "Working directory": "工作目录",
  "Arguments": "参数",
  "Fallback from": "回退来源",
  "Timeline": "时间线",
  "Standard output": "标准输出",
  "Standard error": "标准错误",
  "Exit code": "退出码",
  "Result path": "结果路径",
  "Receipt path": "回执路径",
  "Log path": "日志路径",
  "Generated by Product Shell run logging.": "由 Product Shell 运行日志自动生成。",
  "Review queue": "审阅队列",
  "Execution queue": "执行队列",
  "Open outputs hub": "打开输出总览",
  "Source": "来源",
  "PDF, Markdown, or Repo": "PDF、Markdown 或 Repo",
  PDF: "PDF",
  Markdown: "Markdown",
  Repo: "Repo",
  "No nightly state yet.": "还没有 nightly 状态。",
  "Rerun command": "重跑命令",
  "Rewrite follow-up": "改写后续动作",
  "healthy": "健康",
  warnings: "告警",
  errors: "错误",
  "stdout: {value}": "标准输出：{value}",
  "stderr: {value}": "错误输出：{value}",
  "error: {value}": "错误：{value}",
  "completed": "已完成",
  "failed: {message}": "失败：{message}",
  "status-unknown": "状态未知",
  "command-palette labels refresh after reloading Obsidian.": "命令面板标签会在重载 Obsidian 后刷新。",
  decision: "决策",
  decisions: "决策",
  judgment: "判断",
  judgments: "判断",
  page: "页面",
  pages: "页面",
  archive: "归档",
  // EP-006 jargon → user-friendly Chinese
  stdout: "标准输出",
  stderr: "错误输出",
  error: "错误",
};
const THIN_CURATED_STATUS_LABELS = {
  "pending-review": "待审",
  confirmed: "已确认",
  discarded: "废弃",
};
const THIN_REVIEW_TRANSITION_LABELS = {
  "pending-review": "待审",
  confirmed: "已确认",
  discarded: "废弃",
};
const CURATED_STATUS_LABELS = {
  proposed: "Proposed",
  approved: "Approved",
  "needs-revisit": "Needs revisit",
  superseded: "Superseded",
  tentative: "Tentative",
  tracking: "Tracking",
  confirmed: "Confirmed",
  rejected: "Rejected",
};
const ACTION_STATUS_LABELS = {
  proposed: "Proposed",
  accepted: "Accepted",
  deferred: "Deferred",
  resolved: "Resolved",
  rejected: "Rejected",
};
const REWRITE_STATUS_LABELS = {
  proposed: "Proposed",
  accepted: "Accepted",
  deferred: "Deferred",
  applied: "Applied",
  rejected: "Rejected",
};
const REVIEW_REASON_LABELS = {
  "pending-review": "pending review",
  "overdue-review": "overdue review",
  "escalation-candidate": "escalation candidate",
  "scheduled-review": "scheduled review",
  "missing-counter-evidence": "missing counter evidence",
  "missing-invalidation": "missing invalidation",
  "missing-next-signals": "missing next signals",
  "missing-review-history": "missing review history",
  "citation-drift": "citation drift",
  "citation-snapshot-gap": "citation snapshot gap",
};
