// Constants, default settings, i18n dictionary, and status label maps.

const PLUGIN_ID = "furnace-product-shell";
const VIEW_TYPE_FURNACE_CENTER = "furnace-product-shell-furnace-center";
const VIEW_TYPE_RECENT_RUNS = "furnace-product-shell-recent-runs";
const VIEW_TYPE_REVIEW_CENTER = "furnace-product-shell-review-center";
const VIEW_TYPE_EXECUTION_CENTER = "furnace-product-shell-execution-center";
const SHELL_SUMMARY_PATH = "output/control/shell-summary.json";
const DEFAULT_PROTOCOLS = ["general", "investing", "research", "product", "ops"];
const DEFAULT_LOCALE = "zh";
const DEFAULT_SETTINGS = {
  launcherPath: "scripts/aiwiki-launcher.sh",
  defaultAskMode: "run-ask",
  defaultAskFormat: "report",
  recentRunsLimit: 8,
  showAdvancedCommands: false,
  showHtmlShortcuts: true,
  locale: DEFAULT_LOCALE,
  llmBackend: "",
  llmModel: "",
  llmNvidiaNimApiKey: "",
  llmNvidiaNimBaseUrl: "",
  feishuWebhookUrl: "",
  wecomWebhookUrl: "",
  enabledChannels: [],
  lastViewedTimestamp: "",
  lastKnownReportIds: [],
  onboardingShown: false,
};
const ZH_TEXT = {
  "Advanced": "更多工具",
  "Review {review_count} · execution {execution_count} · recent runs {run_count}": "待审 {review_count} · 待执行 {execution_count} · 运行记录 {run_count}",
  "Furnace Product Shell": "炼丹炉 Product Shell",
  "UI language": "界面语言",
  "Default display language for the Product Shell UI. Command palette labels refresh after reloading Obsidian.": "Product Shell 默认显示语言。修改后，命令面板标签需要重载 Obsidian 才会刷新。",
  Chinese: "中文",
  English: "英文",
  "Aiwiki launcher": "Aiwiki 启动器",
  "Vault-local or absolute launcher path. This vault may point at an external runtime root.": "vault 内相对路径或绝对 launcher 路径。这个 vault 可以指向外部 runtime root。",
  "Default ask mode": "默认 Ask 模式",
  "Choose whether Ask defaults to deterministic `ask` or LLM-backed `run-ask`.": "选择 Ask 默认走 deterministic `ask`，还是 LLM 驱动的 `run-ask`。",
  "Default ask format": "默认 Ask 格式",
  "Default output format for the Ask modal.": "Ask 模态框的默认输出格式。",
  "Recent runs limit": "最近运行保留数",
  "How many plugin-triggered runs to keep in the Product Shell.": "Product Shell 中保留多少条插件触发的运行记录。",
  "Show advanced commands": "显示高级命令",
  "Register review, execution, protocol, and legacy panel commands in the command palette. Reload Obsidian after changing this toggle.": "是否把审阅、执行、协议与旧面板命令注册到命令面板中。修改后需要重载 Obsidian。",
  "Show HTML shortcuts": "显示 HTML 快捷入口",
  "Whether advanced panels should show HTML shortcuts when the summary exposes them.": "当 summary 暴露 HTML 面板时，是否在高级面板里显示 HTML 快捷入口。",
  "Advanced command visibility refreshes after reloading Obsidian.": "高级命令可见性会在重载 Obsidian 后刷新。",
  "LLM backend": "LLM 后端",
  "Select the explicit LLM backend used by run-compile / run-ask / run-nightly. Empty = unconfigured.": "为 run-compile / run-ask / run-nightly 显式选择 LLM 后端。留空 = 未配置。",
  "LLM model": "LLM 模型",
  "Override the model name (e.g. gpt-5.4, claude-sonnet-4.5). Empty = selected backend default strategy (`codex-cli`: `gpt-5.4`; `nvidia-nim-api`: `moonshotai/kimi-k2.5 -> z-ai/glm-5.1 -> minimaxai/minimax-m2.7`).": "覆盖模型名称（如 gpt-5.4、claude-sonnet-4.5）。留空 = 所选后端默认策略（`codex-cli`: `gpt-5.4`；`nvidia-nim-api`: `moonshotai/kimi-k2.5 -> z-ai/glm-5.1 -> minimaxai/minimax-m2.7`）。",
  "route only (no LLM)": "仅路由（无 LLM）",
  "LLM answer (recommended)": "LLM 深度回答（推荐）",
  "NVIDIA NIM API key": "NVIDIA NIM API Key",
  "Optional key for nvidia-nim-api. Stored locally in plugin data. Empty = use AIWIKI_NVIDIA_NIM_API_KEY / NVIDIA_NIM_API_KEY.": "nvidia-nim-api 的可选 API key。本地存储于插件数据中。留空 = 使用 AIWIKI_NVIDIA_NIM_API_KEY / NVIDIA_NIM_API_KEY。",
  "NVIDIA NIM base URL": "NVIDIA NIM Base URL",
  "Override the NVIDIA NIM endpoint. Empty = https://integrate.api.nvidia.com/v1.": "覆盖 NVIDIA NIM 端点。留空 = https://integrate.api.nvidia.com/v1。",
  "LLM settings saved. New runs will use the updated configuration.": "LLM 设置已保存。新的运行将使用更新后的配置。",
  "Notifications (webhook)": "通知（webhook）",
  "Webhook settings are stored only in local plugin data. Failures are not retried. Notifications are only for new reports.": "Webhook 设置仅保存在本地插件数据中。失败不会重试。通知只用于新报告。",
  "Feishu webhook URL": "飞书 webhook URL",
  "WeCom webhook URL": "企业微信 webhook URL",
  "Enable Feishu": "启用飞书",
  "Enable WeCom": "启用企业微信",
  "Universal input": "统一输入",
  "Universal Input": "统一输入",
  "Universal input cannot be empty.": "统一输入不能为空。",
  "Drop URL, PDF, image, repo, note, or question...": "投 URL、PDF、图片、repo、笔记，或直接提问……",
  "Drop file here": "把文件拖到这里",
  Submit: "提交",
  "Invalid input: {message}": "输入无效：{message}",
  "Ask 炼丹炉": "问炼丹炉",
  Question: "问题",
  "Enter the research question...": "输入研究问题……",
  Format: "格式",
  Mode: "模式",
  Protocol: "协议",
  "current protocol": "当前协议",
  Run: "运行",
  Cancel: "取消",
  "Question cannot be empty.": "问题不能为空。",
  "Nothing to copy.": "没有可复制的内容。",
  "Clipboard is not available in this environment.": "当前环境不支持剪贴板。",
  "Copied to clipboard.": "已复制到剪贴板。",
  "LLM backend unavailable; retried with deterministic ask.": "LLM 后端当前不可用，已自动回退到 deterministic ask。",
  "LLM health": "LLM 状态",
  Sync: "同步",
  "Configured route": "当前模型",
  "Last checked": "最近检测",
  "Refreshing shell summary.": "正在刷新 shell-summary。",
  "Latest refresh failed.": "最近一次刷新失败。",
  "Summary ready.": "summary 已就绪。",
  "No recent LLM health check yet.": "还没有最近一次 LLM 状态检查。",
  "LLM is not configured.": "当前没有配置 LLM。",
  "Current route changed since the last recorded ask.": "当前路由已经和最近一次记录的 Ask 不同。",
  degraded: "降级",
  warning: "警告",
  "Deterministic fallback": "本地兜底",
  "Deterministic fallback active": "已使用本地兜底",
  "Recent run-ask succeeded.": "最近一次 run-ask 成功完成。",
  "Recent run-ask fell back to deterministic ask.": "最近一次 run-ask 已回退到 deterministic ask。",
  "Latest run-ask failed without deterministic fallback.": "最近一次 run-ask 失败，且没有进入 deterministic fallback。",
  "No Product Shell ask has been recorded yet.": "当前还没有 Product Shell Ask 记录。",
  "Product Shell ask history matches the current route.": "Product Shell 的 Ask 历史与当前路由一致。",
  "Latest Product Shell ask used {latest}; current route is {current}.": "最近一次 Product Shell Ask 使用的是 {latest}；当前路由是 {current}。",
  "requested {requested} · effective {effective} · available {available}": "请求 {requested} · 生效 {effective} · 可见 {available}",
  "Product Shell runtime can see codex-cli.": "Product Shell 当前 runtime 能看到 codex-cli。",
  "Product Shell runtime cannot see codex-cli. GUI PATH may differ from terminal PATH.": "Product Shell 当前 runtime 看不到 codex-cli，GUI 进程的 PATH 很可能和终端不一致。",
  "No explicit LLM backend is selected. Choose one in Product Shell settings or set AIWIKI_LLM_BACKEND.": "当前没有显式选择 LLM 后端。请在 Product Shell 设置里选择，或设置 AIWIKI_LLM_BACKEND。",
  "Product Shell runtime can see the selected backend {backend}.": "Product Shell 当前 runtime 能看到所选后端 {backend}。",
  "Product Shell runtime cannot see the selected backend {backend}.": "Product Shell 当前 runtime 看不到所选后端 {backend}。",
  "Summary is stale; refresh before trusting the home surface.": "shell-summary 已过期，先 Refresh，再相信首页状态。",
  "Generated {time}": "生成于 {time}",
  "launcher {launcher} · root {root}": "launcher {launcher} · 根目录 {root}",
  Fallback: "回退",
  "Ask modal": "Ask 模态框",
  "Capture Note": "记录笔记",
  Title: "标题",
  "Optional note title...": "可选笔记标题……",
  Kind: "类型",
  Text: "正文",
  "Capture a note, meeting log, or quick observation...": "记录笔记、会议纪要或快速观察……",
  "This writes into raw/inbox through the same launcher/runtime used by CLI commands.": "这会通过与 CLI 相同的 launcher/runtime 写入 raw/inbox。",
  Capture: "记录",
  "Text cannot be empty.": "正文不能为空。",
  "Set Protocol": "设置协议",
  Apply: "应用",
  "Choose a protocol.": "请选择协议。",
  "Set protocol modal": "设置协议模态框",
  "Search 炼丹炉": "搜索炼丹炉",
  Query: "查询",
  "Search wiki/sources, concepts, judgments, decisions, and derived pages...": "搜索 wiki/sources、concepts、judgments、decisions 和 derived 页面……",
  Limit: "数量上限",
  Search: "搜索",
  "Search query cannot be empty.": "搜索词不能为空。",
  "Search modal": "搜索模态框",
  "Run command": "运行命令",
  "Pick context": "选择上下文",
  Close: "关闭",
  Use: "使用",
  "command modal": "命令模态框",
  "context picker": "上下文选择器",
  "{field} cannot be empty.": "{field} 不能为空。",
  "No context is currently available.": "当前没有可用上下文。",
  "No context is currently available; fell back to the manual form.": "当前没有可用上下文，已回退到手动表单。",
  "Open Furnace Center": "打开炉心面板",
  "Open Furnace": "打开炼丹炉",
  "Refresh Furnace Shell": "刷新炼丹炉 Shell",
  "Open Review Center": "打开审阅中心",
  "Open Execution Center": "打开执行中心",
  "Open Recent Runs": "打开最近运行",
  Compile: "编译",
  Ask: "提问",
  "Drop URL": "投网址",
  "Drop File": "投文件",
  "Drop Image": "投图片",
  "Drop Material": "投料",
  "Search Workspace": "搜索工作区",
  Nightly: "夜间巡检",
  "File Back": "回流归档",
  "Review Page": "审阅页面",
  "Review Next Page": "审阅下一页",
  "Batch Review Pages": "批量审阅页面",
  "Review Rewrite": "审阅改写",
  "rewrite proposals: {count}": "改写提案：{count}",
  "Apply Rewrite": "应用改写",
  "Retire Concept": "退役概念",
  "Reactivate Concept": "重新激活概念",
  "Review Action": "审阅动作",
  "Apply Action": "应用动作",
  "Revert Action": "回滚动作",
  "Apply All Accepted Low-Risk Actions": "应用所有已接受的低风险动作",
  "Revert Last Action Batch": "回滚上一批动作",
  "Open Home Note": "打开首页笔记",
  Home: "首页",
  Refresh: "刷新",
  "Recent Runs": "最近运行",
  "Start Here": "从这里开始",
  "Obsidian Product Shell and the launcher CLI share the same runtime: Ask works from both sides, and ingest can happen through Capture Note / raw/inbox / drop-*.": "Obsidian Product Shell 与 launcher CLI 共用同一个 runtime：Ask 两边都能跑，投料可走 Capture Note / raw/inbox / drop-*。",
  "Click Refresh first so shell-summary is generated.": "先点 Refresh，确认 shell-summary 已生成。",
  "Use Capture Note in Obsidian, or use drop note / drop url / drop pdf / drop image / drop repo in the terminal.": "在 Obsidian 里用 Capture Note，或在终端里用 drop note / drop url / drop pdf / drop image / drop repo 投料。",
  "Use the Ask modal when you need to ask a question, or run ./scripts/aiwiki-launcher.sh ask ...": "需要提问时用 Ask modal，或运行 ./scripts/aiwiki-launcher.sh ask ...",
  "Follow single writer for write actions: do not run compile / nightly / apply / revert in Obsidian and the terminal at the same time.": "有写入任务运行时，等它结束后再从另一个入口开始新的写入任务。",
  "Vault runtime unavailable. Missing scaffold or launcher: {missing}": "Vault runtime 不可用。缺少 scaffold 或 launcher：{missing}",
  "Expected a vault scaffold (`raw/wiki/schema/output/.aiwiki`) plus an executable launcher script.": "预期存在 vault scaffold（`raw/wiki/schema/output/.aiwiki`）以及可执行的 launcher 脚本。",
  "shell-summary.json has not been generated yet. Run Refresh, Compile, or Nightly first.": "shell-summary.json 尚未生成。先运行 Refresh、Compile 或 Nightly。",
  "Active Protocol": "当前协议",
  "LLM Backend": "LLM 服务",
  "LLM Model": "LLM 模型",
  "Codex effort": "Codex 档位",
  "Prompt profile": "Prompt 档位",
  "Retry prompt": "重试 Prompt",
  "codex effort {value}": "Codex 档位 {value}",
  "prompt {value}": "Prompt 档位 {value}",
  "retry {value}": "重试 Prompt {value}",
  "Usage Visibility": "Usage 可见性",
  "Pending Reviews": "待审阅",
  Overdue: "逾期",
  Escalation: "升级候选",
  "Recent Outputs": "最近输出",
  "System status": "运行状态",
  "Status checks": "状态检查",
  "Self-check": "自我检查",
  "Make sure frontend state and runtime state still agree.": "确认前端状态和 runtime 状态仍然对应一致。",
  "Runtime contract": "运行时契约",
  "Shell summary": "Shell 摘要",
  "LLM route": "LLM 路由",
  "Backend discovery": "后端发现",
  "Latest ask execution": "最近一次 Ask 执行",
  "Route drift": "路由漂移",
  "Make runtime state explicit before you act.": "先确认当前没有冲突中的写入任务。",
  Ready: "就绪",
  "No command is currently running.": "当前没有任务在运行。",
  "{count} command(s) running right now.": "当前有 {count} 个任务正在运行。",
  "Single writer active: avoid compile / nightly / apply / revert from two surfaces at once.": "已有写入任务在运行；等它结束后再开始新的写入任务。",
  Summary: "摘要",
  "Generated at {generated_at} | contract v{version}": "生成于 {generated_at} | contract v{version}",
  "Review backlog {review_count} | concept backlog {concept_backlog} | retired concepts {retired_concepts}": "审阅积压 {review_count} | 概念积压 {concept_backlog} | 已退役概念 {retired_concepts}",
  "Judgment assets {pages} | strong assets {strong_assets} | attention {attention_pages} | citation drift {citation_drift}": "判断资产 {pages} | 强资产 {strong_assets} | 关注页 {attention_pages} | 引用漂移 {citation_drift}",
  "Knowledge Base": "知识库",
  Sources: "来源",
  Concepts: "概念",
  Judgments: "判断",
  Decisions: "决策",
  Edges: "边",
  "Causal Edges": "因果边",
  "Term Index": "术语索引",
  Dashboard: "仪表盘",
  "⚠️ Drift Warnings": "⚠️ 漂移警告",
  "Suggested Next Actions": "建议下一步动作",
  Today: "今日",
  "(nothing for today)": "今天暂无待处理内容",
  "Needs Decision": "需要判断",
  Proposals: "提案",
  "Today's Reports": "今日报告",
  Completed: "已完成",
  "Suggested Actions": "建议动作",
  "Keep the next safe action visible from the main surface.": "把下一步安全动作直接放在首屏，不藏在 summary 深处。",
  "No suggested next action right now.": "当前没有明确的建议下一步动作。",
  "reason {value}": "原因 {value}",
  Open: "打开",
  "Open report": "打开报告",
  "Open decision": "打开决策",
  "Open judgment": "打开判断",
  "Open Review": "打开审阅",
  "Copy target": "复制目标",
  Report: "报告",
  "Decision page": "决策页",
  "Judgment page": "判断页",
  "Proposal page": "提案页",
  "Graph page": "关系图谱",
  "Review surface": "审阅入口",
  "Workspace page": "工作区页面",
  "Metric alert": "指标提醒",
  "Command prepared for manual confirmation": "命令已准备，复制后人工确认",
  "Previous Reports": "过往报告",
  "(no reports today)": "今天还没有报告",
  "(no previous reports)": "暂无过往报告",
  "Search Results": "搜索结果",
  "No matching pages in the compiled workspace.": "编译后的工作区中没有匹配页面。",
  "Recent Queries": "最近查询",
  "Judgment Focus": "判断焦点",
  "Quick Links": "快捷链接",
  "Plugin-triggered Commands": "插件触发命令",
  "Runtime Events from shell-summary": "来自 shell-summary 的运行事件",
  "Recent Receipts": "最近回执",
  "Review Center": "审阅中心",
  "Review Next": "下一项审阅",
  "Batch Review": "批量审阅",
  "Pending Decisions": "待审决策",
  "Pending Judgments": "待审判断",
  "Overdue Reviews": "逾期审阅",
  "Concept Backlog": "概念积压",
  "Review Concepts": "待审概念",
  "Revisit Concepts": "待回看概念",
  "Retired Concepts": "已退役概念",
  "Next Review": "下一项审阅",
  More: "更多",
  "Batch Suggestions": "批量建议",
  "Judgment Assets": "判断资产",
  "Strong Assets": "强资产",
  "Attention Pages": "关注页",
  "Missing Counter Evidence": "缺少反证",
  "Missing Invalidation": "缺少失效条件",
  "Missing Next Signals": "缺少下一信号",
  "Missing Review History": "缺少审阅历史",
  "Decision Objects": "决策对象",
  "Judgment Objects": "判断对象",
  "Rewrite Proposal Objects": "改写提案对象",
  "Aging Summary": "老化摘要",
  "Overdue pages": "逾期页面",
  "Escalated pages": "升级页面",
  "Scheduled pages": "计划页面",
  none: "无",
  Review: "审阅",
  "Recent Review Events": "最近审阅事件",
  "Governance Links": "治理链接",
  "Execution Center": "执行中心",
  "Apply All Low-Risk": "应用全部低风险项",
  "Revert Last Batch": "回滚上一批",
  "Execution Events": "执行事件",
  "Archive Events": "归档事件",
  "Lifecycle Overrides": "生命周期覆盖",
  "Nightly Runs": "Nightly 次数",
  "Planner Queue": "规划队列",
  "Pending Proposals": "待处理提案",
  Executed: "已执行",
  Unblocked: "已解阻",
  Blocked: "已阻塞",
  "Next Action": "下一动作",
  "Action Control Objects": "动作控制对象",
  "Recent Execution Events": "最近执行事件",
  "Execution Links": "执行链接",
  "Open page": "打开页面",
  "Open first": "打开第一项",
  "Batch review": "批量审阅",
  "Open proposal": "打开提案",
  "Open target": "打开目标",
  "Open primary": "打开主路径",
  "Open receipt": "打开回执",
  "Open result": "打开结果",
  "Copy result path": "复制结果路径",
  "Re-review": "重新审阅",
  "Apply action": "应用动作",
  "Revert action": "回滚动作",
  "Apply archive": "应用归档",
  "Revert archive": "回滚归档",
  "Reactivate concept": "重新激活概念",
  "Review action": "审阅动作",
  "Furnace": "炼丹炉",
  "Furnace Center": "炉心面板",
  "Furnace shell unavailable": "炼丹炉 shell 不可用",
  "Missing runtime paths: {missing}": "缺少运行时路径：{missing}",
  "Furnace Product Shell active protocol {protocol}": "炼丹炉 Product Shell 当前协议 {protocol}",
  " | syncing": " | 同步中",
  " | running {count}": " | 运行中 {count}",
  "Command failed with exit code {code}": "命令失败，退出码 {code}",
  "Capture note modal": "记录笔记模态框",
  "unknown error": "未知错误",
  "No plugin-triggered commands yet.": "当前还没有插件触发的命令。",
  "No shell summary recent runs are available.": "当前没有 shell summary recent runs。",
  "No recent receipts are available.": "当前没有 recent receipts。",
  "No recent outputs are available.": "当前没有 recent outputs。",
  "No recent review events are available.": "当前没有 recent review events。",
  "No recent execution events are available.": "当前没有 recent execution events。",
  "No batch review groups share the same recommended transition.": "当前没有共享推荐状态的批量 review 组。",
  "No explicit next review item is available.": "当前没有显式 next review item。",
  "No explicit decision review object is available.": "当前没有显式 decision review object。",
  "No explicit judgment review object is available.": "当前没有显式 judgment review object。",
  "No explicit rewrite proposal object is available.": "当前没有显式 rewrite proposal object。",
  "No explicit action control object is available.": "当前没有显式 action control object。",
  "No judgment asset focus object is available.": "当前没有 judgment asset focus object。",
  "shell-summary.json is not available yet. Run Refresh, Compile, or Nightly first.": "shell-summary.json 尚未生成。先运行 Refresh / Compile / Nightly 之一。",
  "Repo-local runtime unavailable. Missing: {missing}": "Repo-local runtime 不可用。缺少：{missing}",
  "No visible review backlog item is available; fell back to the manual form.": "当前没有可见的 review backlog 条目，已回退到手动表单。",
  "No reviewable page is available.": "当前没有可 review 的页面。",
  "No shared batch review suggestion is available.": "当前没有共享推荐状态的批量 review 建议。",
  "No visible concept context is available; fell back to the manual form.": "当前没有可见的 concept context，已回退到手动表单。",
  "No visible machine-memory action context is available; fell back to the manual form.": "当前没有可见的 machine-memory action context，已回退到手动表单。",
  "No visible archive context is available; fell back to the manual form.": "当前没有可见的 archive context，已回退到手动表单。",
  "No explicit review transition is available; fell back to the manual form.": "当前没有显式 review transition，已回退到手动表单。",
  "No explicit rewrite transition is available; fell back to the manual form.": "当前没有显式 rewrite transition，已回退到手动表单。",
  "No explicit action transition is available; fell back to the manual form.": "当前没有显式 action transition，已回退到手动表单。",
  "priority": "优先级",
  "score": "分数",
  "review object": "审阅对象",
  "review-object": "审阅对象",
  "judgment asset": "判断资产",
  "Artifact path": "产物路径",
  "Page path": "页面路径",
  "Page paths": "页面路径",
  "Concept slug": "概念 slug",
  "Entry id": "条目 id",
  "Action id": "动作 id",
  "Bundle path": "bundle 路径",
  "Status": "状态",
  "Note": "备注",
  "Confidence": "置信度",
  "Dry run": "仅演练",
  "output/reports/....md": "output/reports/....md",
  "Optional filed-back title": "可选回填标题",
  "wiki/decisions/... or wiki/judgments/...": "wiki/decisions/... 或 wiki/judgments/...",
  "approved / confirmed / needs-revision ...": "approved / confirmed / needs-revision ...",
  "accepted / rejected / needs-revision ...": "accepted / rejected / needs-revision ...",
  "accepted / rejected / ready ...": "accepted / rejected / ready ...",
  "Optional review note": "可选审阅备注",
  "Optional action review note": "可选动作审阅备注",
  "Optional confidence override": "可选置信度覆盖",
  "Optional apply note": "可选应用备注",
  "Optional revert note": "可选回滚备注",
  "Optional reactivate note": "可选重新激活备注",
  "Optional shared batch note": "可选批量共享备注",
  "Optional shared confidence override": "可选共享置信度覆盖",
  "Optional execution bundle path": "可选执行 bundle 路径",
  "Why retire this concept?": "为什么要退役这个概念？",
  "machine-memory action id": "machine-memory 动作 id",
  "manifest/material entry id": "manifest/material 条目 id",
  "wiki/judgments/... (one per line)": "wiki/judgments/...（每行一个）",
  "tracking / needs-revisit / approved ...": "tracking / needs-revisit / approved ...",
  "Run batch": "运行批量操作",
  "Pick Review Page": "选择审阅页面",
  "Pick Batch Review": "选择批量审阅",
  "Pick Rewrite Context": "选择改写上下文",
  "Pick Review Action": "选择审阅动作",
  "Pick Archive Target": "选择归档目标",
  "Pick Archive Revert Target": "选择归档回滚目标",
  "Pick Apply Action": "选择应用动作",
  "Pick Revert Action": "选择回滚动作",
  "Pick Review Transition": "选择审阅迁移",
  "Pick Rewrite Transition": "选择改写迁移",
  "Pick Action Transition": "选择动作迁移",
  "Advance a decision or judgment page through the explicit review workflow.": "通过显式审阅流程推进决策或判断页面。",
  "Advance a concept rewrite proposal through the rewrite workflow.": "通过改写流程推进概念改写提案。",
  "Apply an accepted concept rewrite proposal.": "应用一个已接受的概念改写提案。",
  "Apply an explicit retired override for a concept.": "为概念应用显式 retired 覆盖。",
  "Clear the explicit retired override for a concept.": "清除概念上的显式 retired 覆盖。",
  "Apply a ready archive candidate and pin it to archived.": "应用一个已准备好的归档候选，并将其固定为 archived。",
  "Revert the latest explicit archive transition.": "回滚最近一次显式归档迁移。",
  "Advance a machine-memory repair action through the explicit action workflow.": "通过显式动作流程推进 machine-memory 修复动作。",
  "Apply an accepted low-risk machine-memory repair action.": "应用一个已接受的低风险 machine-memory 修复动作。",
  "Revert the latest low-risk safe apply for a machine-memory action.": "回滚 machine-memory 动作最近一次低风险安全应用。",
  "File an output artifact back into wiki/derived, wiki/decisions, or wiki/judgments.": "将一个输出产物回填到 wiki/derived、wiki/decisions 或 wiki/judgments。",
  "Prefer an explicit review control object before falling back to manual page entry.": "优先使用显式 review control object，再回退到手动输入页面。",
  "Advance multiple review pages that share a safe common transition.": "批量推进共享安全公共迁移的多个审阅页面。",
  "Batch review is only offered when multiple pages share the same preferred or default transition.": "只有多个页面共享相同的推荐或默认迁移时才提供批量审阅。",
  "Prefer an explicit rewrite proposal object before falling back to manual slug entry.": "优先使用显式 rewrite proposal object，再回退到手动输入 slug。",
  "Prefer an explicit action control object before falling back to manual action id entry.": "优先使用显式 action control object，再回退到手动输入 action id。",
  "Prefer an explicit archive control object before falling back to manual entry id.": "优先使用显式 archive control object，再回退到手动输入 entry id。",
  "Choose a valid next status for this review page.": "为这个审阅页面选择一个有效的下一状态。",
  "Choose a valid next status for this rewrite proposal.": "为这个改写提案选择一个有效的下一状态。",
  "Choose a valid next status for this machine-memory action.": "为这个 machine-memory 动作选择一个有效的下一状态。",
  "Batch review requires at least one page path.": "批量审阅至少需要一个页面路径。",
  "share the recommended transition": "共享推荐迁移",
  "actions": "动作",
  "archives": "归档",
  "decision_pages": "决策页面",
  "judgment_pages": "判断页面",
  "rewrite_proposals": "改写提案",
  "derived": "派生产物",
  "Apply Archive": "应用归档",
  "Revert Archive": "回滚归档",
  "Apply rewrite": "应用改写",
  "result-usage": "返回 usage",
  "response-usage": "返回 usage",
  "opaque-cli": "CLI 不透明",
  unconfigured: "未配置",
  unknown: "未知",
  success: "成功",
  running: "运行中",
  failed: "失败",
  default: "默认",
  medium: "中",
  operation: "操作",
  event: "事件",
  results: "结果数",
  query: "查询",
  result: "结果",
  output: "输出",
  receipt: "回执",
  review: "审阅",
  action: "动作",
  context: "上下文",
  command: "命令",
  transition: "迁移",
  card: "卡片",
  drift: "漂移",
  "review-page": "审阅页面",
  "rewrite-proposal": "改写提案",
  "archive-entry": "归档条目",
  "judgment-asset": "判断资产",
  "runtime-event": "运行事件",
  apply: "应用",
  revert: "回滚",
  "file-back": "回流归档",
  "archive-apply": "归档应用",
  "archive-revert": "归档回滚",
  "knowledge-lifecycle-override": "生命周期覆盖",
  general: "通用",
  investing: "投资",
  research: "研究",
  product: "产品",
  ops: "运维",
  source: "来源",
  concept: "概念",
  markdown: "Markdown",
  html: "HTML",
  json: "JSON",
  proposed: "提议",
  approved: "已批准",
  "needs revisit": "需回看",
  superseded: "已替代",
  tentative: "暂定",
  tracking: "跟踪中",
  confirmed: "已确认",
  rejected: "已拒绝",
  accepted: "已接受",
  deferred: "已延期",
  resolved: "已解决",
  applied: "已应用",
  "pending review": "待审阅",
  "overdue review": "逾期审阅",
  "escalation candidate": "升级候选",
  "scheduled review": "计划审阅",
  "missing counter evidence": "缺少反证",
  "missing invalidation": "缺少失效条件",
  "missing next signals": "缺少下一信号",
  "missing review history": "缺少审阅历史",
  "citation drift": "引用漂移",
  "citation snapshot gap": "引用快照缺口",
  "confidence {value}": "置信度 {value}",
  "asset {value}/4": "资产分 {value}/4",
  "history {value}": "历史 {value}",
  "drift {value}": "漂移 {value}",
  "snapshot gaps {value}": "快照缺口 {value}",
  "preferred transition": "推荐迁移",
  "allowed transition": "允许迁移",
  "Manual review...": "手动审阅……",
  "Manual rewrite review...": "手动改写审阅……",
  "Manual action review...": "手动动作审阅……",
  "keep current status and capture note / confidence in the full form": "保留当前状态，并在完整表单里填写 note / confidence",
  "Search completed: {query}": "搜索完成：{query}",
  "Cannot parse command: {command}": "无法解析命令：{command}",
  "No path to open.": "没有可打开的路径。",
  "Unable to open {path}": "无法打开 {path}",
  "Path not found: {path}": "路径不存在：{path}",
  "Unable to open resource: {path}": "无法打开资源：{path}",
  Interaction: "交互",
  "Ask anything about the current workspace.": "围绕当前工作区直接提问或搜索。",
  "Type a question or keyword...": "输入问题或关键词……",
  Send: "发送",
  Materials: "原料投入",
  "Push new material into the furnace.": "把新原料投进炉子，等下一次编译或夜间巡检收敛。",
  "Latest outputs": "最新产出",
  "Open the newest outputs without diving into control surfaces.": "直接打开最新产出，不必先进入复杂控制面板。",
  "View all": "查看全部",
  "No recent outputs yet. Drop material or run a compile.": "还没有最新产出；先投料或运行一次编译。",
  "Daily Digest": "今日简报",
  "A compact pulse for knowledge, review, and nightly health.": "用一张卡片看知识库、审阅和例行检查状态。",
  "Last sync": "最后同步",
  "Summary unavailable. The panel will sync automatically when possible.": "当前还没有 summary；面板会在可用时自动同步。",
  "Advanced Actions": "工具操作",
  "Core workflows stay available here, but hidden by default.": "核心工作流仍然都在，只是默认折叠起来。",
  "Knowledge Compounding Metrics": "知识复利指标",
  "(metrics unavailable; run aiwiki metrics for details)": "指标暂不可用；需要详情时打开指标报告。",
  "Provenance Completeness": "来源完整度",
  "Stale Page Ratio": "过期页面占比",
  "Review Closure Rate (7d)": "审阅完成率（7 天）",
  "Proposal Acceptance Rate": "提案采纳率",
  "Judgment Revisit Rate": "判断复核率",
  "Output File-back Rate": "产出回填率",
  "Elixir Reuse Count": "复用沉淀数",
  "Run `aiwiki metrics --json` for full data.": "完整指标数据可在指标报告中查看。",
  "Quick review": "快速审阅",
  "Quick execution": "快速执行",
  "Latest plugin runs": "最近运行",
  "Latest run": "最近一次运行",
  "No recent plugin runs.": "当前还没有插件运行记录。",
  "No plugin run yet. Send a question or use a command.": "当前还没有插件运行；发送提问或执行一个命令。",
  "Run log": "运行日志",
  "Open log": "打开日志",
  "Copy command": "复制命令",
  "Reveal result": "定位结果",
  "Reveal receipt": "定位回执",
  "Copy receipt path": "复制回执路径",
  "Copy stderr": "复制 stderr",
  "Unable to reveal {path}": "无法定位 {path}",
  "Path revealed: {path}": "已定位 {path}",
  "Path not found: {path}": "路径不存在：{path}",
  "Stage timeline": "阶段事件流",
  "No stage events recorded.": "当前没有记录到阶段事件。",
  Submitted: "已提交",
  "Runtime selected": "运行上下文",
  Executing: "执行中",
  Completed: "已完成",
  Failed: "失败",
  Artifacts: "产物",
  "Sync now": "立即同步",
  "No interaction yet. Ask a question or run a search.": "还没有交互记录；先提问或搜索一次。",
  "backend {value}": "后端 {value}",
  "model {value}": "模型 {value}",
  selected: "初始",
  final: "最终",
  "fallback {value}": "回退 {value}",
  "protocol {value}": "协议 {value}",
  "Re-run": "重新运行",
  " | llm degraded": " | LLM 已降级",
  "Cannot re-run this entry because argv was not recorded.": "这条记录没有保存 argv，暂时无法重新运行。",
  "Command completed successfully.": "命令已成功完成。",
  "Working directory": "工作目录",
  "Arguments": "参数",
  "Fallback from": "回退来源",
  "Timeline": "时间线",
  "Standard output": "标准输出",
  "Standard error": "标准错误",
  "Exit code": "退出码",
  "Result path": "结果路径",
  "Receipt path": "回执路径",
  "Log path": "日志路径",
  "Generated by Product Shell run logging.": "由 Product Shell 运行日志自动生成。",
  "Review queue": "审阅队列",
  "Execution queue": "执行队列",
  "Open outputs hub": "打开输出总览",
  "URL cannot be empty.": "URL 不能为空。",
  "Source cannot be empty.": "来源不能为空。",
  "Drop URL modal": "投网址模态框",
  "Drop File modal": "投文件模态框",
  "Drop Image modal": "投图片模态框",
  "Web URL": "网页 URL",
  "Source": "来源",
  "Source path or URL": "来源路径或 URL",
  "Select local file": "选择本地文件",
  "PDF or Repo": "PDF 或 Repo",
  PDF: "PDF",
  Repo: "Repo",
  "Local PDF path or PDF URL.": "本地 PDF 路径或 PDF URL。",
  "Local repo path or remote git URL.": "本地仓库路径或远端 git URL。",
  "Local image path or image URL.": "本地图片路径或图片 URL。",
  "Repo max files": "Repo 最大文件数",
  "Skip vision analysis": "跳过视觉分析",
  "Drop this web page into raw/inbox.": "把网页抓取进 raw/inbox。",
  "Import a PDF or repo snapshot into raw/inbox.": "把 PDF 或仓库快照投进 raw/inbox。",
  "Import an image into raw/inbox.": "把图片投进 raw/inbox。",
  "No nightly state yet.": "还没有 nightly 状态。",
  "healthy": "健康",
  warnings: "告警",
  errors: "错误",
  "status {status} | started {started}{finished}": "状态 {status} | 开始于 {started}{finished}",
  " | finished {finished}": " | 结束于 {finished}",
  "stdout: {value}": "stdout：{value}",
  "stderr: {value}": "stderr：{value}",
  "error: {value}": "错误：{value}",
  "completed": "已完成",
  "failed: {message}": "失败：{message}",
  "status-unknown": "状态未知",
  "command-palette labels refresh after reloading Obsidian.": "命令面板标签会在重载 Obsidian 后刷新。",
  decision: "决策",
  decisions: "决策",
  judgment: "判断",
  judgments: "判断",
  page: "页面",
  pages: "页面",
  archive: "归档",
};
const CURATED_STATUS_LABELS = {
  proposed: "Proposed",
  approved: "Approved",
  "needs-revisit": "Needs revisit",
  superseded: "Superseded",
  tentative: "Tentative",
  tracking: "Tracking",
  confirmed: "Confirmed",
  rejected: "Rejected",
};
const ACTION_STATUS_LABELS = {
  proposed: "Proposed",
  accepted: "Accepted",
  deferred: "Deferred",
  resolved: "Resolved",
  rejected: "Rejected",
};
const REWRITE_STATUS_LABELS = {
  proposed: "Proposed",
  accepted: "Accepted",
  deferred: "Deferred",
  applied: "Applied",
  rejected: "Rejected",
};
const REVIEW_REASON_LABELS = {
  "pending-review": "pending review",
  "overdue-review": "overdue review",
  "escalation-candidate": "escalation candidate",
  "scheduled-review": "scheduled review",
  "missing-counter-evidence": "missing counter evidence",
  "missing-invalidation": "missing invalidation",
  "missing-next-signals": "missing next signals",
  "missing-review-history": "missing review history",
  "citation-drift": "citation drift",
  "citation-snapshot-gap": "citation snapshot gap",
};
