"""Universal audit stream preview, backfill, and append helpers."""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ..app_state import execution_receipt_history_path, llm_receipt_log_path, runtime_history_path
from ..app_utils import sha256_bytes
from .protocol_learnings import AUDIT_STATE_PATH

AUDIT_STREAM_PATH = ".aiwiki/state/audit.jsonl"


class AuditAppendError(RuntimeError):
    """Raised when the universal audit sink cannot append or inspect audit state."""


@dataclass(frozen=True)
class AuditAppendResult:
    written: bool
    reason: str
    record: dict[str, Any]
    audit_stream_path: str = AUDIT_STREAM_PATH


def append_audit(
    source: str,
    payload: dict[str, Any],
    *,
    event_id: str | None = None,
    timestamp: str | None = None,
    root: Path | None = None,
) -> AuditAppendResult:
    """Append one record to the universal ``audit.jsonl`` stream.

    ``source`` is a stable snake_case writer name (for example
    ``execution_receipts``, ``runtime_history``, ``llm_receipts``, or
    ``protocol_learnings_age``). New writers should use a durable source name
    that describes the append origin, not the transient caller.

    ``payload`` is merged into the persisted audit envelope. For the current
    universal audit stream this preserves the existing on-disk schema:
    ``audit_event_id``, ``source_stream``, ``source_ref``, ``event_type``,
    ``occurred_at``, ``trace_id``, ``subject``, and ``revert_supported``. The
    sink does not wrap the payload in a nested object so old audit readers keep
    working unchanged.

    ``event_id`` is the idempotency key. Existing universal audit writers must
    pass the exact id generated by ``_audit_record`` so backfill and direct
    append dedupe remain byte-for-byte compatible. If omitted, the sink derives
    a deterministic id from ``source`` and the JSON-normalized payload.

    ``timestamp`` is an optional ISO timestamp used as ``occurred_at`` only when
    the payload does not already provide one. If omitted and no occurred-at
    field exists, the current UTC time is used. Appends are idempotent: when the
    same event id already exists in ``audit.jsonl`` no line is written and the
    result is ``AuditAppendResult(written=False, reason="duplicate", ...)``.

    Any filesystem, serialization, or malformed-input failure is raised as an
    explicit ``AuditAppendError`` or ``ValueError``; errors are never silently
    swallowed by the sink.
    """

    if not isinstance(source, str) or not source.strip():
        raise ValueError("source must be a non-empty string.")
    if not isinstance(payload, dict):
        raise ValueError("payload must be a dict.")

    normalized_source = source.strip()
    record = dict(payload)
    record["source_stream"] = str(record.get("source_stream") or normalized_source)
    if record["source_stream"] != normalized_source:
        raise ValueError("payload source_stream must match source.")

    if event_id is None:
        existing_event_id = record.get("audit_event_id")
        if isinstance(existing_event_id, str) and existing_event_id.strip():
            event_id = existing_event_id.strip()
        else:
            digest_payload = json.dumps(
                {"source": normalized_source, "payload": record},
                ensure_ascii=False,
                sort_keys=True,
            )
            event_id = "audit-" + sha256_bytes(digest_payload.encode("utf-8"))[:20]
    if not isinstance(event_id, str) or not event_id.strip():
        raise ValueError("event_id must be a non-empty string when provided.")
    record["audit_event_id"] = event_id.strip()

    if "occurred_at" not in record:
        if timestamp is None:
            timestamp = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
        if not isinstance(timestamp, str) or not timestamp.strip():
            raise ValueError("timestamp must be a non-empty ISO string when provided.")
        record["occurred_at"] = timestamp.strip()

    audit_path = (root or Path.cwd()) / AUDIT_STREAM_PATH
    try:
        if record["audit_event_id"] in _existing_audit_event_ids(audit_path, strict=True):
            return AuditAppendResult(written=False, reason="duplicate", record=record)
        line = json.dumps(record, ensure_ascii=False, sort_keys=True) + "\n"
        audit_path.parent.mkdir(parents=True, exist_ok=True)
        with audit_path.open("a", encoding="utf-8") as handle:
            handle.write(line)
            handle.flush()
            os.fsync(handle.fileno())
    except AuditAppendError:
        raise
    except (OSError, TypeError, ValueError) as exc:
        raise AuditAppendError(f"failed to append audit record to {AUDIT_STREAM_PATH}: {exc}") from exc
    return AuditAppendResult(written=True, reason="appended", record=record)


def preview_universal_audit_stream(root: Path, *, limit: int = 50) -> dict[str, Any]:
    if limit < 1:
        raise ValueError("limit must be a positive integer.")

    records: list[dict[str, Any]] = []
    source_counts = {
        "execution_receipts": 0,
        "llm_receipts": 0,
        "runtime_history": 0,
        "protocol_learnings_age": 0,
    }

    for source_stream, path in (
        ("execution_receipts", execution_receipt_history_path(root)),
        ("llm_receipts", llm_receipt_log_path(root)),
        ("runtime_history", runtime_history_path(root)),
    ):
        rel_path = _known_relative_path(root, path)
        for line_number, document in _iter_jsonl_documents(path):
            source_counts[source_stream] += 1
            if len(records) < limit:
                records.append(_audit_record(source_stream, f"{rel_path}#L{line_number}", document))

    age_audit_path = root / AUDIT_STATE_PATH
    if age_audit_path.exists():
        document = _load_json_document(age_audit_path)
        if document:
            source_counts["protocol_learnings_age"] += 1
            if len(records) < limit:
                records.append(_audit_record("protocol_learnings_age", protocol_learnings_age_source_ref(document), document))

    scanned_count = sum(source_counts.values())
    return {
        "status": "ok",
        "mode": "dry_run",
        "side_effects_allowed": False,
        "audit_stream_path": AUDIT_STREAM_PATH,
        "audit_stream_exists": (root / AUDIT_STREAM_PATH).exists(),
        "scanned_count": scanned_count,
        "returned_count": len(records),
        "limit": limit,
        "source_counts": source_counts,
        "records": records,
    }


def backfill_universal_audit_stream(root: Path, *, limit: int = 50, apply: bool = False) -> dict[str, Any]:
    preview = preview_universal_audit_stream(root, limit=limit)
    audit_path = root / AUDIT_STREAM_PATH
    existing_ids = _existing_audit_event_ids(audit_path)
    appendable = [
        record
        for record in preview["records"]
        if isinstance(record, dict) and str(record.get("audit_event_id") or "") not in existing_ids
    ]
    result = {
        **preview,
        "apply": apply,
        "appended_count": 0,
        "skipped_existing_count": len(preview["records"]) - len(appendable),
    }
    if not apply:
        return result

    for record in appendable:
        append_result = append_audit(
            str(record["source_stream"]),
            record,
            event_id=str(record["audit_event_id"]),
            root=root,
        )
        if append_result.written:
            result["appended_count"] += 1
        elif append_result.reason == "duplicate":
            result["skipped_existing_count"] += 1
    if appendable:
        result["audit_stream_exists"] = True
    return result


def append_universal_audit_record(root: Path, *, source_stream: str, source_ref: str, document: dict[str, Any]) -> dict[str, Any]:
    record = _audit_record(source_stream, source_ref, document)
    result = append_audit(source_stream, record, event_id=str(record["audit_event_id"]), root=root)
    if not result.written:
        return {"status": "skipped_existing", "record": record, "audit_stream_path": AUDIT_STREAM_PATH}
    return {"status": "appended", "record": record, "audit_stream_path": AUDIT_STREAM_PATH}


def protocol_learnings_age_source_ref(document: dict[str, Any]) -> str:
    run_at = document.get("run_at")
    if isinstance(run_at, str) and run_at.strip():
        return f"{AUDIT_STATE_PATH}#run_at={run_at.strip()}"
    return AUDIT_STATE_PATH


def _existing_audit_event_ids(path: Path, *, strict: bool = False) -> set[str]:
    ids: set[str] = set()
    try:
        for _, document in _iter_jsonl_documents(path, strict=strict):
            audit_event_id = document.get("audit_event_id")
            if isinstance(audit_event_id, str) and audit_event_id:
                ids.add(audit_event_id)
    except OSError as exc:
        if strict:
            raise AuditAppendError(f"failed to read existing audit ids from {AUDIT_STREAM_PATH}: {exc}") from exc
        return ids
    return ids


def _iter_jsonl_documents(path: Path, *, strict: bool = False) -> list[tuple[int, dict[str, Any]]]:
    if not path.exists():
        return []
    rows: list[tuple[int, dict[str, Any]]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            payload = line.strip()
            if not payload:
                continue
            try:
                document = json.loads(payload)
            except json.JSONDecodeError as exc:
                if strict:
                    raise AuditAppendError(f"invalid JSON in {path} at line {line_number}: {exc}") from exc
                continue
            if isinstance(document, dict):
                rows.append((line_number, document))
    return rows


def _load_json_document(path: Path) -> dict[str, Any]:
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return document if isinstance(document, dict) else {}


def _audit_record(source_stream: str, source_ref: str, document: dict[str, Any]) -> dict[str, Any]:
    event_type = _event_type(source_stream, document)
    occurred_at = _first_string(
        document,
        (
            "applied_at",
            "generated_at",
            "run_at",
            "created_at",
            "recorded_at",
            "completed_at",
            "started_at",
            "timestamp",
            "updated_at",
        ),
    )
    trace_id = _trace_id(document)
    subject = _subject(document, event_type)
    digest_payload = json.dumps(
        {
            "source_stream": source_stream,
            "source_ref": source_ref,
            "event_type": event_type,
            "subject": subject,
        },
        ensure_ascii=False,
        sort_keys=True,
    )
    record = {
        "audit_event_id": "audit-" + sha256_bytes(digest_payload.encode("utf-8"))[:20],
        "source_stream": source_stream,
        "source_ref": source_ref,
        "event_type": event_type,
        "occurred_at": occurred_at,
        "trace_id": trace_id,
        "subject": subject,
        "revert_supported": bool(document.get("revert_supported", False)),
    }
    if source_stream == "llm_receipts":
        record["raw_response_path"] = str(document.get("raw_response_path") or "")
    return record


def _event_type(source_stream: str, document: dict[str, Any]) -> str:
    if source_stream == "protocol_learnings_age":
        return "protocol_learnings_age"
    for key in ("operation", "event_type", "status", "kind"):
        value = document.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return source_stream


def _trace_id(document: dict[str, Any]) -> str:
    value = document.get("trace_id")
    if isinstance(value, str):
        return value
    values = document.get("trace_ids")
    if isinstance(values, list):
        for item in values:
            if isinstance(item, str) and item:
                return item
    return ""


def _subject(document: dict[str, Any], event_type: str) -> dict[str, str]:
    subject_kind = _first_string(
        document,
        (
            "subject_kind",
            "proposal_kind",
            "kind",
            "event_type",
            "operation",
        ),
    )
    subject_id = _first_string(
        document,
        (
            "subject_id",
            "action_id",
            "batch_id",
            "proposal_id",
            "run_id",
            "signal_id",
            "elixir_id",
            "learning_id",
        ),
    )
    if not subject_kind:
        subject_kind = event_type
    return {"kind": subject_kind, "id": subject_id}


def _first_string(document: dict[str, Any], keys: tuple[str, ...]) -> str:
    for key in keys:
        value = document.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return ""


def _known_relative_path(root: Path, path: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)
