"""Core application logic for the aiwiki MVP."""

from __future__ import annotations

from .config import LLMConfig
from functools import wraps
from pathlib import Path
from typing import Any
from . import app_compile as _app_compile
from . import app_content as _app_content
from . import app_memory as _app_memory
from . import app_protocol as _app_protocol
from . import app_state as _app_state
from . import app_utils as _app_utils

_raw_compile_wiki = _app_compile.compile_wiki
_raw_ask_question = _app_compile.ask_question
_raw_build_ranking_source_record = _app_compile.build_ranking_source_record
_raw_build_ranking_concept_record = _app_compile.build_ranking_concept_record
_raw_transition_profile = _app_content.transition_profile
_raw_curated_page_transition_profile = _app_content.curated_page_transition_profile
_raw_rewrite_transition_profile = _app_content.rewrite_transition_profile
_raw_action_transition_profile = _app_content.action_transition_profile
_raw_archive_transition_profile = _app_content.archive_transition_profile
_raw_shell_review_controls = _app_memory.shell_review_controls
_raw_shell_action_control_objects = _app_memory.shell_action_control_objects
_raw_shell_archive_control_objects = _app_memory.shell_archive_control_objects
_raw_shell_execution_controls = _app_memory.shell_execution_controls

_RUNTIME_LOCK_GUARD = _app_utils._RUNTIME_LOCK_GUARD
_RUNTIME_LOCKS = _app_utils._RUNTIME_LOCKS
TEXT_EXTENSIONS = _app_utils.TEXT_EXTENSIONS
STOP_WORDS = _app_utils.STOP_WORDS
PROVENANCE_PATH_PATTERN = _app_utils.PROVENANCE_PATH_PATTERN
ISO_DATETIME_PATTERN = _app_utils.ISO_DATETIME_PATTERN
runtime_lock_path = _app_utils.runtime_lock_path
runtime_write_lock = _app_utils.runtime_write_lock
runtime_write_operation = _app_utils.runtime_write_operation
utc_now = _app_utils.utc_now
parse_iso_datetime = _app_utils.parse_iso_datetime
slugify = _app_utils.slugify
detect_kind = _app_utils.detect_kind
sha256_bytes = _app_utils.sha256_bytes
sha256_file = _app_utils.sha256_file
relative_path = _app_utils.relative_path
next_identifier = _app_utils.next_identifier
next_available_stem = _app_utils.next_available_stem
read_text_preview = _app_utils.read_text_preview
raw_note_metadata = _app_utils.raw_note_metadata
render_scalar = _app_utils.render_scalar
render_frontmatter = _app_utils.render_frontmatter
parse_scalar = _app_utils.parse_scalar
parse_frontmatter = _app_utils.parse_frontmatter
strip_frontmatter = _app_utils.strip_frontmatter
upsert_markdown_section = _app_utils.upsert_markdown_section
normalize_workspace_path = _app_utils.normalize_workspace_path
extract_provenance_paths = _app_utils.extract_provenance_paths
evidence_path_digest = _app_utils.evidence_path_digest
build_citation_snapshots = _app_utils.build_citation_snapshots
parse_citation_snapshots = _app_utils.parse_citation_snapshots
analyze_citation_snapshots = _app_utils.analyze_citation_snapshots
replace_first_markdown_heading = _app_utils.replace_first_markdown_heading
first_markdown_heading = _app_utils.first_markdown_heading
write_if_changed = _app_utils.write_if_changed
normalize_generated_artifact_content = _app_utils.normalize_generated_artifact_content
write_if_changed_ignoring_timestamps = _app_utils.write_if_changed_ignoring_timestamps
render_json_document = _app_utils.render_json_document
normalize_generated_state_document = _app_utils.normalize_generated_state_document
write_json_document_if_changed_ignoring_generated_timestamps = _app_utils.write_json_document_if_changed_ignoring_generated_timestamps
compiled_source_sha = _app_utils.compiled_source_sha
html_safe_json_literal = _app_utils.html_safe_json_literal
tokenize = _app_utils.tokenize

DEFAULT_PROTOCOL = _app_state.DEFAULT_PROTOCOL
KNOWLEDGE_LIFECYCLE_KINDS = _app_state.KNOWLEDGE_LIFECYCLE_KINDS
KNOWLEDGE_LIFECYCLE_STATES = _app_state.KNOWLEDGE_LIFECYCLE_STATES
manifest_path = _app_state.manifest_path
default_manifest = _app_state.default_manifest
load_manifest = _app_state.load_manifest
machine_memory_state_path = _app_state.machine_memory_state_path
machine_memory_graph_path = _app_state.machine_memory_graph_path
machine_memory_graph_html_path = _app_state.machine_memory_graph_html_path
review_center_html_path = _app_state.review_center_html_path
furnace_center_html_path = _app_state.furnace_center_html_path
shell_summary_path = _app_state.shell_summary_path
execution_center_html_path = _app_state.execution_center_html_path
execution_audit_html_path = _app_state.execution_audit_html_path
machine_memory_history_path = _app_state.machine_memory_history_path
machine_memory_drift_report_path = _app_state.machine_memory_drift_report_path
graph_health_report_path = _app_state.graph_health_report_path
machine_memory_topology_path = _app_state.machine_memory_topology_path
machine_memory_actions_path = _app_state.machine_memory_actions_path
machine_memory_repair_plan_path = _app_state.machine_memory_repair_plan_path
execution_center_path = _app_state.execution_center_path
execution_audit_path = _app_state.execution_audit_path
agent_workbench_path = _app_state.agent_workbench_path
agent_pack_path = _app_state.agent_pack_path
output_packs_index_path = _app_state.output_packs_index_path
domain_pilots_path = _app_state.domain_pilots_path
execution_receipt_history_path = _app_state.execution_receipt_history_path
concept_quality_path = _app_state.concept_quality_path
concept_rewrite_index_path = _app_state.concept_rewrite_index_path
concept_rewrite_proposal_page_path = _app_state.concept_rewrite_proposal_page_path
machine_memory_action_state_path = _app_state.machine_memory_action_state_path
concept_rewrite_state_path = _app_state.concept_rewrite_state_path
manual_link_state_path = _app_state.manual_link_state_path
repair_backlog_path = _app_state.repair_backlog_path
judgment_assets_path = _app_state.judgment_assets_path
cognitive_history_path = _app_state.cognitive_history_path
aging_report_path = _app_state.aging_report_path
nightly_health_state_path = _app_state.nightly_health_state_path
compile_state_path = _app_state.compile_state_path
concept_build_state_path = _app_state.concept_build_state_path
machine_memory_build_state_path = _app_state.machine_memory_build_state_path
ranking_build_state_path = _app_state.ranking_build_state_path
output_pack_build_state_path = _app_state.output_pack_build_state_path
domain_pilot_build_state_path = _app_state.domain_pilot_build_state_path
material_state_path = _app_state.material_state_path
active_corpora_state_path = _app_state.active_corpora_state_path
runtime_history_path = _app_state.runtime_history_path
material_routing_state_path = _app_state.material_routing_state_path
archive_candidates_state_path = _app_state.archive_candidates_state_path
knowledge_lifecycle_state_path = _app_state.knowledge_lifecycle_state_path
knowledge_lifecycle_override_state_path = _app_state.knowledge_lifecycle_override_state_path
material_archive_state_path = _app_state.material_archive_state_path
load_json_document = _app_state.load_json_document
save_json_document = _app_state.save_json_document
load_jsonl_documents = _app_state.load_jsonl_documents
default_compile_state = _app_state.default_compile_state
load_compile_state = _app_state.load_compile_state
save_compile_state = _app_state.save_compile_state
default_concept_build_state = _app_state.default_concept_build_state
load_concept_build_state = _app_state.load_concept_build_state
save_concept_build_state = _app_state.save_concept_build_state
default_machine_memory_build_state = _app_state.default_machine_memory_build_state
load_machine_memory_build_state = _app_state.load_machine_memory_build_state
save_machine_memory_build_state = _app_state.save_machine_memory_build_state
default_ranking_build_state = _app_state.default_ranking_build_state
load_ranking_build_state = _app_state.load_ranking_build_state
save_ranking_build_state = _app_state.save_ranking_build_state
default_output_pack_build_state = _app_state.default_output_pack_build_state
load_output_pack_build_state = _app_state.load_output_pack_build_state
save_output_pack_build_state = _app_state.save_output_pack_build_state
default_domain_pilot_build_state = _app_state.default_domain_pilot_build_state
load_domain_pilot_build_state = _app_state.load_domain_pilot_build_state
save_domain_pilot_build_state = _app_state.save_domain_pilot_build_state
default_material_state = _app_state.default_material_state
load_material_state = _app_state.load_material_state
save_material_state = _app_state.save_material_state
default_active_corpora_state = _app_state.default_active_corpora_state
load_active_corpora_state = _app_state.load_active_corpora_state
save_active_corpora_state = _app_state.save_active_corpora_state
load_runtime_history = _app_state.load_runtime_history
append_runtime_history = _app_state.append_runtime_history
default_material_routing_state = _app_state.default_material_routing_state
load_material_routing_state = _app_state.load_material_routing_state
save_material_routing_state = _app_state.save_material_routing_state
default_archive_candidates_state = _app_state.default_archive_candidates_state
load_archive_candidates_state = _app_state.load_archive_candidates_state
save_archive_candidates_state = _app_state.save_archive_candidates_state
default_knowledge_lifecycle_state = _app_state.default_knowledge_lifecycle_state
load_knowledge_lifecycle_state = _app_state.load_knowledge_lifecycle_state
save_knowledge_lifecycle_state = _app_state.save_knowledge_lifecycle_state
default_knowledge_lifecycle_override_state = _app_state.default_knowledge_lifecycle_override_state
load_knowledge_lifecycle_override_state = _app_state.load_knowledge_lifecycle_override_state
save_knowledge_lifecycle_override_state = _app_state.save_knowledge_lifecycle_override_state
ensure_knowledge_lifecycle_override_state = _app_state.ensure_knowledge_lifecycle_override_state
active_knowledge_lifecycle_overrides = _app_state.active_knowledge_lifecycle_overrides
default_material_archive_state = _app_state.default_material_archive_state
load_material_archive_state = _app_state.load_material_archive_state
save_material_archive_state = _app_state.save_material_archive_state
active_material_archive_entries = _app_state.active_material_archive_entries
active_archived_material_ids = _app_state.active_archived_material_ids
material_archive_action_id = _app_state.material_archive_action_id
default_machine_memory_action_state = _app_state.default_machine_memory_action_state
load_machine_memory_action_state = _app_state.load_machine_memory_action_state
save_machine_memory_action_state = _app_state.save_machine_memory_action_state
load_machine_memory = _app_state.load_machine_memory
default_concept_rewrite_state = _app_state.default_concept_rewrite_state
load_concept_rewrite_state = _app_state.load_concept_rewrite_state
save_concept_rewrite_state = _app_state.save_concept_rewrite_state
default_manual_link_state = _app_state.default_manual_link_state
load_manual_link_state = _app_state.load_manual_link_state
save_manual_link_state = _app_state.save_manual_link_state

LAYOUT_DIRS = _app_protocol.LAYOUT_DIRS
DEFAULT_SCHEMA_FILES = _app_protocol.DEFAULT_SCHEMA_FILES
DEFAULT_DASHBOARD_FILES = _app_protocol.DEFAULT_DASHBOARD_FILES
CURATED_ASSET_SECTION_ORDER = _app_protocol.CURATED_ASSET_SECTION_ORDER
PROTOCOL_SECTION_FILES = _app_protocol.PROTOCOL_SECTION_FILES
PROTOCOL_SECTION_TITLES = _app_protocol.PROTOCOL_SECTION_TITLES
PROTOCOL_LIBRARY = _app_protocol.PROTOCOL_LIBRARY
PROTOCOL_REVIEW_WINDOWS = _app_protocol.PROTOCOL_REVIEW_WINDOWS
PROTOCOL_CLASSIFICATION_MARKERS = _app_protocol.PROTOCOL_CLASSIFICATION_MARKERS
PROTOCOL_PROMOTION_PREFIXES = _app_protocol.PROTOCOL_PROMOTION_PREFIXES
PROTOCOL_FOCUS_KEYWORDS = _app_protocol.PROTOCOL_FOCUS_KEYWORDS
PROTOCOL_ACTION_KIND_WEIGHTS = _app_protocol.PROTOCOL_ACTION_KIND_WEIGHTS
PROTOCOL_OUTPUT_GUIDANCE = _app_protocol.PROTOCOL_OUTPUT_GUIDANCE
CONFLICT_SIGNAL_PAIRS = _app_protocol.CONFLICT_SIGNAL_PAIRS
EVIDENCE_GAP_MARKERS = _app_protocol.EVIDENCE_GAP_MARKERS
DECISION_STATUSES = _app_protocol.DECISION_STATUSES
JUDGMENT_STATUSES = _app_protocol.JUDGMENT_STATUSES
ACTION_STATUSES = _app_protocol.ACTION_STATUSES
REWRITE_PROPOSAL_STATUSES = _app_protocol.REWRITE_PROPOSAL_STATUSES
ACTIVE_CORPUS_STATUSES = _app_protocol.ACTIVE_CORPUS_STATUSES
ARCHIVE_CANDIDATE_STATUSES = _app_protocol.ARCHIVE_CANDIDATE_STATUSES
PENDING_DECISION_REVIEW_STATUSES = _app_protocol.PENDING_DECISION_REVIEW_STATUSES
PENDING_JUDGMENT_REVIEW_STATUSES = _app_protocol.PENDING_JUDGMENT_REVIEW_STATUSES
PENDING_ACTION_STATUSES = _app_protocol.PENDING_ACTION_STATUSES
PENDING_REWRITE_PROPOSAL_STATUSES = _app_protocol.PENDING_REWRITE_PROPOSAL_STATUSES
LOW_RISK_APPLYABLE_ACTION_KINDS = _app_protocol.LOW_RISK_APPLYABLE_ACTION_KINDS
ACTIVE_CORPUS_TTL = _app_protocol.ACTIVE_CORPUS_TTL
ARCHIVE_QUERY_STALE_AFTER = _app_protocol.ARCHIVE_QUERY_STALE_AFTER
EXECUTION_BAND_LABELS = _app_protocol.EXECUTION_BAND_LABELS
AGING_WINDOWS_DAYS = _app_protocol.AGING_WINDOWS_DAYS
AUTO_PROMOTION_MIN_OCCURRENCES = _app_protocol.AUTO_PROMOTION_MIN_OCCURRENCES
AUTO_PROMOTION_FORMATS = _app_protocol.AUTO_PROMOTION_FORMATS
DECISION_QUERY_MARKERS = _app_protocol.DECISION_QUERY_MARKERS
JUDGMENT_QUERY_MARKERS = _app_protocol.JUDGMENT_QUERY_MARKERS
AGENT_PACK_LIBRARY = _app_protocol.AGENT_PACK_LIBRARY
ensure_layout = _app_protocol.ensure_layout
ensure_runtime_schema = _app_protocol.ensure_runtime_schema
ensure_runtime_dashboards = _app_protocol.ensure_runtime_dashboards
protocol_state_path = _app_protocol.protocol_state_path
default_protocol_state = _app_protocol.default_protocol_state
protocol_title = _app_protocol.protocol_title
protocol_summary = _app_protocol.protocol_summary
render_protocol_library_index = _app_protocol.render_protocol_library_index
render_protocol_overview = _app_protocol.render_protocol_overview
render_protocol_section = _app_protocol.render_protocol_section
ensure_protocol_scaffold = _app_protocol.ensure_protocol_scaffold
available_protocols = _app_protocol.available_protocols
protocol_descriptor = _app_protocol.protocol_descriptor
load_protocol_state = _app_protocol.load_protocol_state
resolve_protocol = _app_protocol.resolve_protocol
protocol_runtime_summary = _app_protocol.protocol_runtime_summary
protocol_focus_score = _app_protocol.protocol_focus_score
page_focus_score = _app_protocol.page_focus_score
action_focus_score = _app_protocol.action_focus_score
entry_focus_score = _app_protocol.entry_focus_score
concept_focus_score = _app_protocol.concept_focus_score
protocol_output_guidance = _app_protocol.protocol_output_guidance
protocol_paths = _app_protocol.protocol_paths
schedule_review_windows = _app_protocol.schedule_review_windows
save_manifest = _app_protocol.save_manifest

sync_manifest_with_raw = _app_content.sync_manifest_with_raw
ingest_source = _app_content.ingest_source
render_source_page = _app_content.render_source_page
render_source_page_with_state = _app_content.render_source_page_with_state
concept_candidates = _app_content.concept_candidates
preserved_section = _app_content.preserved_section
normalized_markdown_section_lines = _app_content.normalized_markdown_section_lines
curated_asset_placeholder_lines = _app_content.curated_asset_placeholder_lines
render_curated_asset_sections = _app_content.render_curated_asset_sections
render_review_history_section = _app_content.render_review_history_section
curated_asset_section_snapshot = _app_content.curated_asset_section_snapshot
append_review_history_entry = _app_content.append_review_history_entry
review_history_entries = _app_content.review_history_entries
concept_label_to_slug = _app_content.concept_label_to_slug
concept_label_to_title = _app_content.concept_label_to_title
entry_concept_terms = _app_content.entry_concept_terms
source_summary_or_preview = _app_content.source_summary_or_preview
active_manual_source_concept_links = _app_content.active_manual_source_concept_links
concept_source_input_signature = _app_content.concept_source_input_signature
build_concept_records = _app_content.build_concept_records
concept_source_signature = _app_content.concept_source_signature
concept_source_pages = _app_content.concept_source_pages
machine_memory_source_input_signature = _app_content.machine_memory_source_input_signature
machine_memory_concept_input_signature = _app_content.machine_memory_concept_input_signature
concept_render_signature = _app_content.concept_render_signature
render_concept_conflict_lines = _app_content.render_concept_conflict_lines
render_concept_gap_lines = _app_content.render_concept_gap_lines
render_concept_page = _app_content.render_concept_page
render_sources_index = _app_content.render_sources_index
render_concepts_index = _app_content.render_concepts_index
default_curated_status = _app_content.default_curated_status
valid_curated_statuses = _app_content.valid_curated_statuses
page_needs_review = _app_content.page_needs_review
evaluate_page_aging = _app_content.evaluate_page_aging
collect_aging_signals = _app_content.collect_aging_signals
display_curated_status = _app_content.display_curated_status
curated_page_template = _app_content.curated_page_template
action_needs_review = _app_content.action_needs_review
display_action_status = _app_content.display_action_status
rewrite_proposal_needs_review = _app_content.rewrite_proposal_needs_review
display_rewrite_proposal_status = _app_content.display_rewrite_proposal_status
rewrite_proposal_status_rank = _app_content.rewrite_proposal_status_rank
transition_profile = _app_content.transition_profile
curated_page_transition_profile = _app_content.curated_page_transition_profile
rewrite_transition_profile = _app_content.rewrite_transition_profile
action_transition_profile = _app_content.action_transition_profile
archive_transition_profile = _app_content.archive_transition_profile
sort_curated_pages = _app_content.sort_curated_pages
collect_curated_pages = _app_content.collect_curated_pages
review_queue = _app_content.review_queue
knowledge_lifecycle_invalidation_signals = _app_content.knowledge_lifecycle_invalidation_signals
knowledge_lifecycle_active_corpus_ids = _app_content.knowledge_lifecycle_active_corpus_ids
knowledge_lifecycle_classification = _app_content.knowledge_lifecycle_classification
concept_lifecycle_invalidation_signals = _app_content.concept_lifecycle_invalidation_signals
concept_lifecycle_review_signals = _app_content.concept_lifecycle_review_signals
concept_lifecycle_classification = _app_content.concept_lifecycle_classification
build_knowledge_lifecycle_entry = _app_content.build_knowledge_lifecycle_entry
build_concept_lifecycle_entry = _app_content.build_concept_lifecycle_entry
apply_knowledge_lifecycle_override = _app_content.apply_knowledge_lifecycle_override
knowledge_lifecycle_counts = _app_content.knowledge_lifecycle_counts
display_knowledge_lifecycle_state = _app_content.display_knowledge_lifecycle_state
display_protocol_relevance_mode = _app_content.display_protocol_relevance_mode
display_protocol_relevance_ambiguity = _app_content.display_protocol_relevance_ambiguity
select_knowledge_lifecycle_entries = _app_content.select_knowledge_lifecycle_entries
sort_knowledge_lifecycle_entries = _app_content.sort_knowledge_lifecycle_entries
render_knowledge_lifecycle_entry_summary = _app_content.render_knowledge_lifecycle_entry_summary
knowledge_lifecycle_governance_summary = _app_content.knowledge_lifecycle_governance_summary
concept_protocol_relevance_for_source = _app_content.concept_protocol_relevance_for_source
concept_protocol_relevance = _app_content.concept_protocol_relevance
concept_protocol_ambiguity_state = _app_content.concept_protocol_ambiguity_state
concept_lifecycle_matches_protocol = _app_content.concept_lifecycle_matches_protocol
protocol_related_concept_lifecycle_summary = _app_content.protocol_related_concept_lifecycle_summary
refresh_knowledge_lifecycle_state = _app_content.refresh_knowledge_lifecycle_state
build_knowledge_lifecycle_document = _app_content.build_knowledge_lifecycle_document
collect_machine_memory_actions = _app_content.collect_machine_memory_actions
collect_machine_memory_action_aging = _app_content.collect_machine_memory_action_aging
action_priority_rank = _app_content.action_priority_rank
action_status_rank = _app_content.action_status_rank
action_supports_low_risk_apply = _app_content.action_supports_low_risk_apply
execution_policy_profile = _app_content.execution_policy_profile
execution_band_label = _app_content.execution_band_label
PATCH_ROLE_LABELS = _app_content.PATCH_ROLE_LABELS
PATCH_PLAN_TEMPLATES = _app_content.PATCH_PLAN_TEMPLATES
PATCH_PLAN_AUXILIARY_PATHS = _app_content.PATCH_PLAN_AUXILIARY_PATHS
PROTOCOL_PATCH_HINTS = _app_content.PROTOCOL_PATCH_HINTS
patch_role_for_path = _app_content.patch_role_for_path
patch_sections_for_action = _app_content.patch_sections_for_action
patch_summary_for_action = _app_content.patch_summary_for_action
patch_mode_for_action = _app_content.patch_mode_for_action
build_page_patch_plan = _app_content.build_page_patch_plan
safe_apply_preview = _app_content.safe_apply_preview
build_execution_bundle = _app_content.build_execution_bundle
execution_bundle_digest = _app_content.execution_bundle_digest
load_execution_bundle = _app_content.load_execution_bundle
build_execution_receipt = _app_content.build_execution_receipt
build_material_archive_bundle = _app_content.build_material_archive_bundle
build_material_archive_receipt = _app_content.build_material_archive_receipt
append_execution_receipt_history = _app_content.append_execution_receipt_history
load_execution_receipt_history = _app_content.load_execution_receipt_history
remove_stale_generated_execution_proposal_pages = _app_content.remove_stale_generated_execution_proposal_pages
remove_stale_generated_execution_bundle_files = _app_content.remove_stale_generated_execution_bundle_files
remove_stale_generated_markdown_files = _app_content.remove_stale_generated_markdown_files
describe_machine_memory_action = _app_content.describe_machine_memory_action
build_machine_memory_repair_plan = _app_content.build_machine_memory_repair_plan
normalize_query_signature = _app_content.normalize_query_signature
classify_recurring_output_kind = _app_content.classify_recurring_output_kind
promotion_page_title = _app_content.promotion_page_title
collect_output_artifacts = _app_content.collect_output_artifacts
collect_output_density_artifacts = _app_content.collect_output_density_artifacts
collect_recent_output_artifacts = _app_content.collect_recent_output_artifacts
find_promoted_curated_page = _app_content.find_promoted_curated_page
recurring_promotion_needs_refresh = _app_content.recurring_promotion_needs_refresh
annotate_recurring_promotion = _app_content.annotate_recurring_promotion
render_curated_page_summary = _app_content.render_curated_page_summary
render_curated_index = _app_content.render_curated_index
render_judgment_assets = _app_content.render_judgment_assets
render_cognitive_history = _app_content.render_cognitive_history
compact_section_lines = _app_content.compact_section_lines
workspace_link = _app_content.workspace_link
pack_workspace_link = _app_content.pack_workspace_link
load_workspace_markdown = _app_content.load_workspace_markdown
workspace_file_signature = _app_content.workspace_file_signature
output_pack_review_candidates = _app_content.output_pack_review_candidates
output_pack_reviewed_candidates = _app_content.output_pack_reviewed_candidates
output_pack_repair_plan_candidates = _app_content.output_pack_repair_plan_candidates
output_pack_state_records = _app_content.output_pack_state_records
output_pack_group_is_reusable = _app_content.output_pack_group_is_reusable
output_pack_lifecycle_summary_input_signature = _app_content.output_pack_lifecycle_summary_input_signature
output_pack_review_group_input_signature = _app_content.output_pack_review_group_input_signature
output_pack_decision_memo_group_input_signature = _app_content.output_pack_decision_memo_group_input_signature
output_pack_sop_group_input_signature = _app_content.output_pack_sop_group_input_signature
build_output_pack_review_packs = _app_content.build_output_pack_review_packs
build_output_pack_decision_memos = _app_content.build_output_pack_decision_memos
build_output_pack_sop_drafts = _app_content.build_output_pack_sop_drafts
build_output_packs = _app_content.build_output_packs
build_output_packs_incremental = _app_content.build_output_packs_incremental
render_output_packs_index = _app_content.render_output_packs_index
domain_pilots_index_path = _app_content.domain_pilots_index_path
pilot_scorecards_dir = _app_content.pilot_scorecards_dir
pilot_scorecard_path = _app_content.pilot_scorecard_path
pilot_stage = _app_content.pilot_stage
domain_pilot_state_scorecard = _app_content.domain_pilot_state_scorecard
domain_pilot_scorecard_is_reusable = _app_content.domain_pilot_scorecard_is_reusable
domain_pilot_protocol_inputs = _app_content.domain_pilot_protocol_inputs
domain_pilot_protocol_input_signature = _app_content.domain_pilot_protocol_input_signature
build_domain_pilot_scorecard = _app_content.build_domain_pilot_scorecard
build_domain_pilots = _app_content.build_domain_pilots
build_domain_pilots_incremental = _app_content.build_domain_pilots_incremental
render_domain_pilots_index = _app_content.render_domain_pilots_index
render_agent_pack = _app_content.render_agent_pack
render_agent_workbench = _app_content.render_agent_workbench
render_review_queue = _app_content.render_review_queue
render_aging_report = _app_content.render_aging_report
render_review_center_html = _app_content.render_review_center_html
protocol_scorecard = _app_content.protocol_scorecard
protocol_output_pack_rows = _app_content.protocol_output_pack_rows
protocol_execution_receipts = _app_content.protocol_execution_receipts
furnace_quick_commands = _app_content.furnace_quick_commands
render_furnace_center = _app_content.render_furnace_center
render_furnace_center_html = _app_content.render_furnace_center_html
render_compile_status = _app_content.render_compile_status
render_master_index = _app_content.render_master_index
ensure_wiki_log = _app_content.ensure_wiki_log
append_wiki_log = _app_content.append_wiki_log
remove_stale_generated_concept_pages = _app_content.remove_stale_generated_concept_pages
review_packs_dir = _app_content.review_packs_dir
decision_memos_dir = _app_content.decision_memos_dir
sop_drafts_dir = _app_content.sop_drafts_dir
pack_stem = _app_content.pack_stem
review_pack_path = _app_content.review_pack_path
decision_memo_path = _app_content.decision_memo_path
sop_draft_path = _app_content.sop_draft_path
execution_proposals_dir = _app_content.execution_proposals_dir
execution_proposal_path = _app_content.execution_proposal_path
execution_bundles_dir = _app_content.execution_bundles_dir
execution_bundle_path = _app_content.execution_bundle_path
execution_receipts_dir = _app_content.execution_receipts_dir
execution_receipt_path = _app_content.execution_receipt_path
manifest_change_summary = _app_content.manifest_change_summary
summarize_runtime_event_for_shell = _app_content.summarize_runtime_event_for_shell
routing_snapshot_for_protocol = _app_content.routing_snapshot_for_protocol
entry_lookup_maps = _app_content.entry_lookup_maps
entry_ids_from_paths = _app_content.entry_ids_from_paths
_validate_rewrite_candidate_markdown = _app_content._validate_rewrite_candidate_markdown
rewrite_proposal_candidate_is_current = _app_content.rewrite_proposal_candidate_is_current
rewrite_proposal_is_apply_ready = _app_content.rewrite_proposal_is_apply_ready
validate_low_risk_action_targets = _app_content.validate_low_risk_action_targets
placeholder_concept_slugs = _app_content.placeholder_concept_slugs
concept_summary_is_placeholder = _app_content.concept_summary_is_placeholder
concept_quality_tokens = _app_content.concept_quality_tokens
load_source_page_context = _app_content.load_source_page_context
detect_concept_conflict_signals = _app_content.detect_concept_conflict_signals
detect_concept_gap_signals = _app_content.detect_concept_gap_signals
concept_rewrite_priority = _app_content.concept_rewrite_priority
concept_rewrite_strategy = _app_content.concept_rewrite_strategy
repair_execution_proposals = _app_content.repair_execution_proposals
build_concept_quality = _app_content.build_concept_quality

shell_recent_runs = _app_memory.shell_recent_runs
shell_recent_receipts = _app_memory.shell_recent_receipts
shell_review_controls = _app_memory.shell_review_controls
shell_action_control_objects = _app_memory.shell_action_control_objects
shell_archive_control_objects = _app_memory.shell_archive_control_objects
shell_execution_controls = _app_memory.shell_execution_controls
shell_links = _app_memory.shell_links
shell_capabilities = _app_memory.shell_capabilities
shell_protocol_state = _app_memory.shell_protocol_state
build_shell_summary = _app_memory.build_shell_summary
write_shell_summary = _app_memory.write_shell_summary
concept_page_path = _app_memory.concept_page_path
concept_lifecycle_entry = _app_memory.concept_lifecycle_entry
question_signature = _app_memory.question_signature
timestamp_is_newer = _app_memory.timestamp_is_newer
update_latest_timestamp = _app_memory.update_latest_timestamp
protocol_hints_for_material = _app_memory.protocol_hints_for_material
recency_score_for_timestamp = _app_memory.recency_score_for_timestamp
QUERY_TIME_FOCUS_MARKERS = _app_memory.QUERY_TIME_FOCUS_MARKERS
machine_memory_query_time_focus = _app_memory.machine_memory_query_time_focus
machine_memory_source_runtime_record = _app_memory.machine_memory_source_runtime_record
material_protocol_score = _app_memory.material_protocol_score
material_graph_context = _app_memory.material_graph_context
material_routing_selected_as = _app_memory.material_routing_selected_as
temperature_from_routing = _app_memory.temperature_from_routing
source_ids_for_citations = _app_memory.source_ids_for_citations
scan_material_reference_state = _app_memory.scan_material_reference_state
build_material_routing_snapshot = _app_memory.build_material_routing_snapshot
material_top_protocols = _app_memory.material_top_protocols
cross_protocol_bridge_entry = _app_memory.cross_protocol_bridge_entry
build_material_routing_entry = _app_memory.build_material_routing_entry
archive_candidate_reactivation_signals = _app_memory.archive_candidate_reactivation_signals
build_archive_candidate_state = _app_memory.build_archive_candidate_state
routing_bridge_recall_ids = _app_memory.routing_bridge_recall_ids
active_corpus_bridge_evidence_ids = _app_memory.active_corpus_bridge_evidence_ids
reconcile_active_corpora_state = _app_memory.reconcile_active_corpora_state
refresh_material_state = _app_memory.refresh_material_state
build_material_state_documents = _app_memory.build_material_state_documents
upsert_active_corpus = _app_memory.upsert_active_corpus
build_machine_memory = _app_memory.build_machine_memory
plan_machine_memory_build = _app_memory.plan_machine_memory_build
machine_memory_snapshot_is_reusable = _app_memory.machine_memory_snapshot_is_reusable
reuse_machine_memory_core = _app_memory.reuse_machine_memory_core
build_machine_memory_health = _app_memory.build_machine_memory_health
reconcile_machine_memory_actions = _app_memory.reconcile_machine_memory_actions
machine_memory_digest = _app_memory.machine_memory_digest
build_machine_memory_graph = _app_memory.build_machine_memory_graph
render_machine_memory_graph_html = _app_memory.render_machine_memory_graph_html
build_machine_memory_adjacency = _app_memory.build_machine_memory_adjacency
build_machine_memory_query = _app_memory.build_machine_memory_query
build_machine_memory_query_routes = _app_memory.build_machine_memory_query_routes
ranked_machine_memory_anchor_nodes = _app_memory.ranked_machine_memory_anchor_nodes
shortest_machine_memory_path = _app_memory.shortest_machine_memory_path
render_machine_memory_route = _app_memory.render_machine_memory_route
machine_memory_node_metadata = _app_memory.machine_memory_node_metadata
summarize_machine_memory_transition = _app_memory.summarize_machine_memory_transition
append_machine_memory_history = _app_memory.append_machine_memory_history
render_drift_report = _app_memory.render_drift_report
render_graph_health = _app_memory.render_graph_health
render_machine_memory_index = _app_memory.render_machine_memory_index
render_machine_memory_topology = _app_memory.render_machine_memory_topology
render_machine_memory_actions = _app_memory.render_machine_memory_actions
render_machine_memory_repair_plan = _app_memory.render_machine_memory_repair_plan
render_execution_proposal_page = _app_memory.render_execution_proposal_page
render_execution_center = _app_memory.render_execution_center
render_execution_center_html = _app_memory.render_execution_center_html
collect_execution_consistency_signals = _app_memory.collect_execution_consistency_signals
build_execution_audit_snapshot = _app_memory.build_execution_audit_snapshot
render_execution_audit = _app_memory.render_execution_audit
render_execution_audit_html = _app_memory.render_execution_audit_html
render_concept_quality = _app_memory.render_concept_quality
concept_page_snapshot = _app_memory.concept_page_snapshot
concept_rewrite_proposal_digest = _app_memory.concept_rewrite_proposal_digest
reconcile_concept_rewrite_proposals = _app_memory.reconcile_concept_rewrite_proposals
render_concept_rewrite_proposal_page = _app_memory.render_concept_rewrite_proposal_page
render_concept_rewrite_index = _app_memory.render_concept_rewrite_index
store_concept_rewrite_candidate = _app_memory.store_concept_rewrite_candidate

Finding = _app_compile.Finding
set_active_protocol = _app_compile.set_active_protocol
render_protocols_dashboard = _app_compile.render_protocols_dashboard
promote_recurring_outputs = _app_compile.promote_recurring_outputs
build_agent_packs = _app_compile.build_agent_packs
compile_wiki = _app_compile.compile_wiki
ranking_source_record_is_reusable = _app_compile.ranking_source_record_is_reusable
ranking_concept_record_is_reusable = _app_compile.ranking_concept_record_is_reusable
ranking_source_summary_or_preview = _app_compile.ranking_source_summary_or_preview
ranking_source_input_signature = _app_compile.ranking_source_input_signature
build_ranking_source_record = _app_compile.build_ranking_source_record
ranking_concept_input_signature = _app_compile.ranking_concept_input_signature
build_ranking_concept_record = _app_compile.build_ranking_concept_record
build_ranking_state = _app_compile.build_ranking_state
rank_concepts = _app_compile.rank_concepts
source_page_is_stale = _app_compile.source_page_is_stale
source_page_requires_compile = _app_compile.source_page_requires_compile
concept_page_requires_compile = _app_compile.concept_page_requires_compile
wiki_requires_compile = _app_compile.wiki_requires_compile
rank_sources = _app_compile.rank_sources
machine_memory_query_plan_lines = _app_compile.machine_memory_query_plan_lines
render_report = _app_compile.render_report
render_slides = _app_compile.render_slides
render_figure_brief = _app_compile.render_figure_brief
ask_question = _app_compile.ask_question
file_back = _app_compile.file_back
_save_machine_memory_action_records = _app_compile._save_machine_memory_action_records
review_concept_rewrite = _app_compile.review_concept_rewrite
apply_concept_rewrite = _app_compile.apply_concept_rewrite
refresh_knowledge_lifecycle_runtime = _app_compile.refresh_knowledge_lifecycle_runtime
retire_concept = _app_compile.retire_concept
reactivate_concept = _app_compile.reactivate_concept
review_machine_memory_action = _app_compile.review_machine_memory_action
apply_machine_memory_action = _app_compile.apply_machine_memory_action
revert_machine_memory_action = _app_compile.revert_machine_memory_action
apply_material_archive = _app_compile.apply_material_archive
revert_material_archive = _app_compile.revert_material_archive
review_page = _app_compile.review_page
pending_source_summary_ids = _app_compile.pending_source_summary_ids
lint_wiki = _app_compile.lint_wiki
render_repair_backlog = _app_compile.render_repair_backlog
write_nightly_health = _app_compile.write_nightly_health
nightly_health = _app_compile.nightly_health
shell_status = _app_compile.shell_status

def _sync_facade_bindings():
    _app_content.entry_concept_terms = entry_concept_terms
    _app_compile.entry_concept_terms = entry_concept_terms
    _app_content.utc_now = utc_now
    _app_memory.utc_now = utc_now
    _app_compile.utc_now = utc_now
    _app_content.transition_profile = transition_profile
    _app_content.valid_curated_statuses = valid_curated_statuses
    _app_memory.valid_curated_statuses = valid_curated_statuses
    _app_memory.transition_profile = transition_profile
    _app_memory.curated_page_transition_profile = curated_page_transition_profile
    _app_memory.rewrite_transition_profile = rewrite_transition_profile
    _app_memory.action_transition_profile = action_transition_profile
    _app_memory.archive_transition_profile = archive_transition_profile
    _app_memory.shell_review_controls = shell_review_controls
    _app_memory.shell_action_control_objects = shell_action_control_objects
    _app_memory.shell_archive_control_objects = shell_archive_control_objects
    _app_memory.shell_execution_controls = shell_execution_controls
    _app_compile.compile_wiki = compile_wiki
    _app_compile.build_machine_memory = build_machine_memory
    _app_compile.build_ranking_source_record = build_ranking_source_record
    _app_compile.build_ranking_concept_record = build_ranking_concept_record
    _app_content.build_output_pack_review_packs = build_output_pack_review_packs
    _app_content.build_output_pack_decision_memos = build_output_pack_decision_memos
    _app_content.build_output_pack_sop_drafts = build_output_pack_sop_drafts
    _app_content.build_domain_pilot_scorecard = build_domain_pilot_scorecard
    _app_compile.build_output_pack_review_packs = build_output_pack_review_packs
    _app_compile.build_output_pack_decision_memos = build_output_pack_decision_memos
    _app_compile.build_output_pack_sop_drafts = build_output_pack_sop_drafts

def _wrap_synced_export(raw_func):
    @wraps(raw_func)
    def wrapper(*args, **kwargs):
        _sync_facade_bindings()
        return raw_func(*args, **kwargs)
    return wrapper

_AUTO_SYNC_EXPORTS = (
    "ensure_layout",
    "ensure_runtime_schema",
    "ensure_runtime_dashboards",
    "protocol_state_path",
    "default_protocol_state",
    "protocol_title",
    "protocol_summary",
    "render_protocol_library_index",
    "render_protocol_overview",
    "render_protocol_section",
    "ensure_protocol_scaffold",
    "available_protocols",
    "protocol_descriptor",
    "load_protocol_state",
    "resolve_protocol",
    "protocol_runtime_summary",
    "protocol_focus_score",
    "page_focus_score",
    "action_focus_score",
    "entry_focus_score",
    "concept_focus_score",
    "protocol_output_guidance",
    "protocol_paths",
    "schedule_review_windows",
    "save_manifest",
    "sync_manifest_with_raw",
    "ingest_source",
    "render_source_page",
    "render_source_page_with_state",
    "concept_candidates",
    "preserved_section",
    "normalized_markdown_section_lines",
    "curated_asset_placeholder_lines",
    "render_curated_asset_sections",
    "render_review_history_section",
    "curated_asset_section_snapshot",
    "append_review_history_entry",
    "review_history_entries",
    "concept_label_to_slug",
    "concept_label_to_title",
    "entry_concept_terms",
    "source_summary_or_preview",
    "active_manual_source_concept_links",
    "concept_source_input_signature",
    "build_concept_records",
    "concept_source_signature",
    "concept_source_pages",
    "machine_memory_source_input_signature",
    "machine_memory_concept_input_signature",
    "concept_render_signature",
    "render_concept_conflict_lines",
    "render_concept_gap_lines",
    "render_concept_page",
    "render_sources_index",
    "render_concepts_index",
    "default_curated_status",
    "valid_curated_statuses",
    "page_needs_review",
    "evaluate_page_aging",
    "collect_aging_signals",
    "display_curated_status",
    "curated_page_template",
    "action_needs_review",
    "display_action_status",
    "rewrite_proposal_needs_review",
    "display_rewrite_proposal_status",
    "rewrite_proposal_status_rank",
    "transition_profile",
    "curated_page_transition_profile",
    "rewrite_transition_profile",
    "action_transition_profile",
    "archive_transition_profile",
    "sort_curated_pages",
    "collect_curated_pages",
    "review_queue",
    "knowledge_lifecycle_invalidation_signals",
    "knowledge_lifecycle_active_corpus_ids",
    "knowledge_lifecycle_classification",
    "concept_lifecycle_invalidation_signals",
    "concept_lifecycle_review_signals",
    "concept_lifecycle_classification",
    "build_knowledge_lifecycle_entry",
    "build_concept_lifecycle_entry",
    "apply_knowledge_lifecycle_override",
    "knowledge_lifecycle_counts",
    "display_knowledge_lifecycle_state",
    "display_protocol_relevance_mode",
    "display_protocol_relevance_ambiguity",
    "select_knowledge_lifecycle_entries",
    "sort_knowledge_lifecycle_entries",
    "render_knowledge_lifecycle_entry_summary",
    "knowledge_lifecycle_governance_summary",
    "concept_protocol_relevance_for_source",
    "concept_protocol_relevance",
    "concept_protocol_ambiguity_state",
    "concept_lifecycle_matches_protocol",
    "protocol_related_concept_lifecycle_summary",
    "refresh_knowledge_lifecycle_state",
    "build_knowledge_lifecycle_document",
    "collect_machine_memory_actions",
    "collect_machine_memory_action_aging",
    "action_priority_rank",
    "action_status_rank",
    "action_supports_low_risk_apply",
    "execution_policy_profile",
    "execution_band_label",
    "patch_role_for_path",
    "patch_sections_for_action",
    "patch_summary_for_action",
    "patch_mode_for_action",
    "build_page_patch_plan",
    "safe_apply_preview",
    "build_execution_bundle",
    "execution_bundle_digest",
    "load_execution_bundle",
    "build_execution_receipt",
    "build_material_archive_bundle",
    "build_material_archive_receipt",
    "append_execution_receipt_history",
    "load_execution_receipt_history",
    "remove_stale_generated_execution_proposal_pages",
    "remove_stale_generated_execution_bundle_files",
    "remove_stale_generated_markdown_files",
    "describe_machine_memory_action",
    "build_machine_memory_repair_plan",
    "normalize_query_signature",
    "classify_recurring_output_kind",
    "promotion_page_title",
    "collect_output_artifacts",
    "collect_output_density_artifacts",
    "collect_recent_output_artifacts",
    "find_promoted_curated_page",
    "recurring_promotion_needs_refresh",
    "annotate_recurring_promotion",
    "render_curated_page_summary",
    "render_curated_index",
    "render_judgment_assets",
    "render_cognitive_history",
    "compact_section_lines",
    "workspace_link",
    "pack_workspace_link",
    "load_workspace_markdown",
    "workspace_file_signature",
    "output_pack_review_candidates",
    "output_pack_reviewed_candidates",
    "output_pack_repair_plan_candidates",
    "output_pack_state_records",
    "output_pack_group_is_reusable",
    "output_pack_lifecycle_summary_input_signature",
    "output_pack_review_group_input_signature",
    "output_pack_decision_memo_group_input_signature",
    "output_pack_sop_group_input_signature",
    "build_output_pack_review_packs",
    "build_output_pack_decision_memos",
    "build_output_pack_sop_drafts",
    "build_output_packs",
    "build_output_packs_incremental",
    "render_output_packs_index",
    "domain_pilots_index_path",
    "pilot_scorecards_dir",
    "pilot_scorecard_path",
    "pilot_stage",
    "domain_pilot_state_scorecard",
    "domain_pilot_scorecard_is_reusable",
    "domain_pilot_protocol_inputs",
    "domain_pilot_protocol_input_signature",
    "build_domain_pilot_scorecard",
    "build_domain_pilots",
    "build_domain_pilots_incremental",
    "render_domain_pilots_index",
    "render_agent_pack",
    "render_agent_workbench",
    "render_review_queue",
    "render_aging_report",
    "render_review_center_html",
    "protocol_scorecard",
    "protocol_output_pack_rows",
    "protocol_execution_receipts",
    "furnace_quick_commands",
    "render_furnace_center",
    "render_furnace_center_html",
    "render_compile_status",
    "render_master_index",
    "ensure_wiki_log",
    "append_wiki_log",
    "remove_stale_generated_concept_pages",
    "review_packs_dir",
    "decision_memos_dir",
    "sop_drafts_dir",
    "pack_stem",
    "review_pack_path",
    "decision_memo_path",
    "sop_draft_path",
    "execution_proposals_dir",
    "execution_proposal_path",
    "execution_bundles_dir",
    "execution_bundle_path",
    "execution_receipts_dir",
    "execution_receipt_path",
    "manifest_change_summary",
    "summarize_runtime_event_for_shell",
    "routing_snapshot_for_protocol",
    "entry_lookup_maps",
    "entry_ids_from_paths",
    "rewrite_proposal_candidate_is_current",
    "rewrite_proposal_is_apply_ready",
    "validate_low_risk_action_targets",
    "placeholder_concept_slugs",
    "concept_summary_is_placeholder",
    "concept_quality_tokens",
    "load_source_page_context",
    "detect_concept_conflict_signals",
    "detect_concept_gap_signals",
    "concept_rewrite_priority",
    "concept_rewrite_strategy",
    "repair_execution_proposals",
    "build_concept_quality",
    "shell_recent_runs",
    "shell_recent_receipts",
    "shell_review_controls",
    "shell_action_control_objects",
    "shell_archive_control_objects",
    "shell_execution_controls",
    "shell_links",
    "shell_capabilities",
    "shell_protocol_state",
    "build_shell_summary",
    "write_shell_summary",
    "concept_page_path",
    "concept_lifecycle_entry",
    "question_signature",
    "timestamp_is_newer",
    "update_latest_timestamp",
    "protocol_hints_for_material",
    "recency_score_for_timestamp",
    "machine_memory_query_time_focus",
    "machine_memory_source_runtime_record",
    "material_protocol_score",
    "material_graph_context",
    "material_routing_selected_as",
    "temperature_from_routing",
    "source_ids_for_citations",
    "scan_material_reference_state",
    "build_material_routing_snapshot",
    "material_top_protocols",
    "cross_protocol_bridge_entry",
    "build_material_routing_entry",
    "archive_candidate_reactivation_signals",
    "build_archive_candidate_state",
    "routing_bridge_recall_ids",
    "active_corpus_bridge_evidence_ids",
    "reconcile_active_corpora_state",
    "refresh_material_state",
    "build_material_state_documents",
    "upsert_active_corpus",
    "build_machine_memory",
    "plan_machine_memory_build",
    "machine_memory_snapshot_is_reusable",
    "reuse_machine_memory_core",
    "build_machine_memory_health",
    "reconcile_machine_memory_actions",
    "machine_memory_digest",
    "build_machine_memory_graph",
    "render_machine_memory_graph_html",
    "build_machine_memory_adjacency",
    "build_machine_memory_query",
    "build_machine_memory_query_routes",
    "ranked_machine_memory_anchor_nodes",
    "shortest_machine_memory_path",
    "render_machine_memory_route",
    "machine_memory_node_metadata",
    "summarize_machine_memory_transition",
    "append_machine_memory_history",
    "render_drift_report",
    "render_graph_health",
    "render_machine_memory_index",
    "render_machine_memory_topology",
    "render_machine_memory_actions",
    "render_machine_memory_repair_plan",
    "render_execution_proposal_page",
    "render_execution_center",
    "render_execution_center_html",
    "collect_execution_consistency_signals",
    "build_execution_audit_snapshot",
    "render_execution_audit",
    "render_execution_audit_html",
    "render_concept_quality",
    "concept_page_snapshot",
    "concept_rewrite_proposal_digest",
    "reconcile_concept_rewrite_proposals",
    "render_concept_rewrite_proposal_page",
    "render_concept_rewrite_index",
    "store_concept_rewrite_candidate",
    "set_active_protocol",
    "render_protocols_dashboard",
    "promote_recurring_outputs",
    "build_agent_packs",
    "compile_wiki",
    "ranking_source_record_is_reusable",
    "ranking_concept_record_is_reusable",
    "ranking_source_summary_or_preview",
    "ranking_source_input_signature",
    "build_ranking_source_record",
    "ranking_concept_input_signature",
    "build_ranking_concept_record",
    "build_ranking_state",
    "rank_concepts",
    "source_page_is_stale",
    "source_page_requires_compile",
    "concept_page_requires_compile",
    "wiki_requires_compile",
    "rank_sources",
    "machine_memory_query_plan_lines",
    "render_report",
    "render_slides",
    "render_figure_brief",
    "ask_question",
    "file_back",
    "review_concept_rewrite",
    "apply_concept_rewrite",
    "refresh_knowledge_lifecycle_runtime",
    "retire_concept",
    "reactivate_concept",
    "review_machine_memory_action",
    "apply_machine_memory_action",
    "revert_machine_memory_action",
    "apply_material_archive",
    "revert_material_archive",
    "review_page",
    "pending_source_summary_ids",
    "lint_wiki",
    "render_repair_backlog",
    "write_nightly_health",
    "nightly_health",
    "shell_status",
)
for _export_name in _AUTO_SYNC_EXPORTS:
    globals()[_export_name] = _wrap_synced_export(globals()[_export_name])
del _export_name

def compile_wiki(*args, **kwargs):
    _sync_facade_bindings()
    return _raw_compile_wiki(*args, **kwargs)

def ask_question(*args, **kwargs):
    _sync_facade_bindings()
    return _raw_ask_question(*args, **kwargs)

def build_concept_records(*args, **kwargs):
    _sync_facade_bindings()
    return _app_content.build_concept_records(*args, **kwargs)

def build_output_packs(*args, **kwargs):
    _sync_facade_bindings()
    return _app_content.build_output_packs(*args, **kwargs)

def build_output_packs_incremental(*args, **kwargs):
    _sync_facade_bindings()
    return _app_content.build_output_packs_incremental(*args, **kwargs)

def build_domain_pilots(*args, **kwargs):
    _sync_facade_bindings()
    return _app_content.build_domain_pilots(*args, **kwargs)

def build_domain_pilots_incremental(*args, **kwargs):
    _sync_facade_bindings()
    return _app_content.build_domain_pilots_incremental(*args, **kwargs)

def build_shell_summary(*args, **kwargs):
    _sync_facade_bindings()
    return _app_memory.build_shell_summary(*args, **kwargs)

def build_ranking_source_record(*args, **kwargs):
    _sync_facade_bindings()
    return _raw_build_ranking_source_record(*args, **kwargs)

def build_ranking_concept_record(*args, **kwargs):
    _sync_facade_bindings()
    return _raw_build_ranking_concept_record(*args, **kwargs)

def build_ranking_state(*args, **kwargs):
    _sync_facade_bindings()
    return _app_compile.build_ranking_state(*args, **kwargs)

def rank_concepts(*args, **kwargs):
    _sync_facade_bindings()
    return _app_compile.rank_concepts(*args, **kwargs)

def rank_sources(*args, **kwargs):
    _sync_facade_bindings()
    return _app_compile.rank_sources(*args, **kwargs)

def promote_recurring_outputs(*args, **kwargs):
    _sync_facade_bindings()
    return _app_compile.promote_recurring_outputs(*args, **kwargs)

def file_back(*args, **kwargs):
    _sync_facade_bindings()
    return _app_compile.file_back(*args, **kwargs)

def review_concept_rewrite(*args, **kwargs):
    _sync_facade_bindings()
    return _app_compile.review_concept_rewrite(*args, **kwargs)

def apply_concept_rewrite(*args, **kwargs):
    _sync_facade_bindings()
    return _app_compile.apply_concept_rewrite(*args, **kwargs)

def review_machine_memory_action(*args, **kwargs):
    _sync_facade_bindings()
    return _app_compile.review_machine_memory_action(*args, **kwargs)

def apply_machine_memory_action(*args, **kwargs):
    _sync_facade_bindings()
    return _app_compile.apply_machine_memory_action(*args, **kwargs)

def revert_machine_memory_action(*args, **kwargs):
    _sync_facade_bindings()
    return _app_compile.revert_machine_memory_action(*args, **kwargs)

def apply_material_archive(*args, **kwargs):
    _sync_facade_bindings()
    return _app_compile.apply_material_archive(*args, **kwargs)

def revert_material_archive(*args, **kwargs):
    _sync_facade_bindings()
    return _app_compile.revert_material_archive(*args, **kwargs)

def review_page(*args, **kwargs):
    _sync_facade_bindings()
    return _app_compile.review_page(*args, **kwargs)

def nightly_health(*args, **kwargs):
    _sync_facade_bindings()
    return _app_compile.nightly_health(*args, **kwargs)

def transition_profile(*args, **kwargs):
    return _raw_transition_profile(*args, **kwargs)

def curated_page_transition_profile(*args, **kwargs):
    _sync_facade_bindings()
    return _raw_curated_page_transition_profile(*args, **kwargs)

def rewrite_transition_profile(*args, **kwargs):
    _sync_facade_bindings()
    return _raw_rewrite_transition_profile(*args, **kwargs)

def action_transition_profile(*args, **kwargs):
    _sync_facade_bindings()
    return _raw_action_transition_profile(*args, **kwargs)

def archive_transition_profile(*args, **kwargs):
    _sync_facade_bindings()
    return _raw_archive_transition_profile(*args, **kwargs)

def shell_review_controls(*args, **kwargs):
    _sync_facade_bindings()
    return _raw_shell_review_controls(*args, **kwargs)

def shell_action_control_objects(*args, **kwargs):
    _sync_facade_bindings()
    return _raw_shell_action_control_objects(*args, **kwargs)

def shell_archive_control_objects(*args, **kwargs):
    _sync_facade_bindings()
    return _raw_shell_archive_control_objects(*args, **kwargs)

def shell_execution_controls(root: Path, memory: dict[str, Any]) -> dict[str, Any]:
    _sync_facade_bindings()
    return _raw_shell_execution_controls(root, memory)

# Product shell compatibility anchors (implementation moved to app_memory.py).
# "current_status": str(page.get("status") or ""),
# current["can_refresh_review"] = bool(valid_curated_statuses(str(current.get("kind") or "")))
# "can_refresh_review": status in REWRITE_PROPOSAL_STATUSES,
# "can_refresh_review": bool(action.get("active", True)) and status in ACTION_STATUSES,
# "review_controls": review_controls,
# "execution_controls": shell_execution_controls(root, memory),
