"""Content/source/lifecycle logic extracted from aiwiki.app.

OWNER STATUS: facade. DO NOT ADD LOGIC HERE.
New code must import from `aiwiki.content.*` (primary owner) directly.
This file exists only to preserve external import paths and test patch seams.

EP-017C step 5: fully migrated. This module is now a thin facade that re-exports
symbols from `.content.*` (primary owners), plus late re-exports from
`.app_lifecycle` and `.app_render`. The only non-re-export imports below are
facade patch seams kept so that `content.*` submodules can access them via
`from .. import app_content as _facade; _facade.<name>(...)` (see e.g.
`content/io.py::save_manifest` and `content/memory.py::PENDING_ACTION_STATUSES`).
"""

from __future__ import annotations

from .app_protocol import PENDING_ACTION_STATUSES, save_manifest  # noqa: F401
from .app_utils import parse_frontmatter  # noqa: F401
from .content.concepts import (  # noqa: F401
    _concept_summary_matches_legacy_placeholder,
    _normalize_summary_snippet,
    build_concept_quality,
    build_concept_records,
    concept_candidates,
    concept_hardness_rank,
    concept_label_to_slug,
    concept_label_to_title,
    concept_quality_band,
    concept_quality_metrics,
    concept_quality_tokens,
    concept_render_signature,
    concept_rewrite_priority,
    concept_rewrite_strategy,
    concept_source_freshness_score,
    concept_source_input_signature,
    concept_source_pages,
    concept_source_signature,
    detect_concept_conflict_signals,
    detect_concept_gap_signals,
    entry_concept_terms,
    normalize_concept_hardness,
    parse_causal_links,
    render_concept_causal_lines,
    render_concept_conflict_lines,
    render_concept_gap_lines,
    render_concept_page,
    render_concept_summary_fallback,
    render_concepts_index,
    render_sources_index,
)
from .content.io import (  # noqa: F401
    active_manual_source_concept_links,
    annotate_recurring_promotion,
    append_review_history_entry,
    collect_output_artifacts,
    collect_output_density_artifacts,
    collect_recent_output_artifacts,
    curated_asset_placeholder_lines,
    curated_asset_section_snapshot,
    entry_ids_from_paths,
    entry_lookup_maps,
    find_promoted_curated_page,
    ingest_source,
    load_source_page_context,
    manifest_change_summary,
    normalized_markdown_section_lines,
    preserved_section,
    recurring_promotion_needs_refresh,
    render_curated_asset_sections,
    render_review_history_section,
    render_source_page,
    render_source_page_with_state,
    review_history_entries,
    routing_snapshot_for_protocol,
    source_summary_or_preview,
    summarize_runtime_event_for_shell,
    sync_manifest_with_raw,
)
from .content.memory import (  # noqa: F401
    PATCH_PLAN_AUXILIARY_PATHS,
    PATCH_PLAN_TEMPLATES,
    PATCH_ROLE_LABELS,
    PROTOCOL_PATCH_HINTS,
    _validate_rewrite_candidate_markdown,
    action_priority_rank,
    action_status_rank,
    action_supports_low_risk_apply,
    append_execution_policy_decisions,
    build_machine_memory_repair_plan,
    build_page_patch_plan,
    build_planner_state,
    collect_machine_memory_action_aging,
    collect_machine_memory_actions,
    concept_summary_is_placeholder,
    derive_proposal_dependencies,
    describe_machine_memory_action,
    execution_band_label,
    execution_policy_decision_record,
    execution_policy_profile,
    load_execution_policy_decision_history,
    load_execution_receipt_history,
    machine_memory_concept_input_signature,
    machine_memory_source_input_signature,
    patch_mode_for_action,
    patch_role_for_path,
    patch_sections_for_action,
    patch_summary_for_action,
    placeholder_concept_slugs,
    proposal_dependency_weight,
    proposal_impact_score,
    proposal_rollback_summary,
    proposals_overlap,
    remove_stale_generated_execution_bundle_files,
    remove_stale_generated_execution_proposal_pages,
    remove_stale_generated_markdown_files,
    repair_execution_proposals,
    rewrite_proposal_candidate_is_current,
    rewrite_proposal_is_apply_ready,
    safe_apply_preview,
    validate_low_risk_action_targets,
)
from .content.outputs import (  # noqa: F401
    classify_recurring_output_kind,
    normalize_query_signature,
    promotion_page_title,
)

# The following `from .app_lifecycle` / `from .app_render` late re-exports must
# execute AFTER this module's top-level imports have resolved, since those two
# modules import from `app_content` at module load time. The explicit isort split
# prevents ruff/isort from hoisting the late `from ...` statements above this line.

# isort: split


from .app_lifecycle import (  # noqa: E402
    action_needs_review,
    action_transition_profile,
    apply_knowledge_lifecycle_override,
    archive_transition_profile,
    build_concept_lifecycle_entry,
    build_knowledge_lifecycle_document,
    build_knowledge_lifecycle_entry,
    collect_aging_signals,
    collect_curated_pages,
    concept_lifecycle_classification,
    concept_lifecycle_invalidation_signals,
    concept_lifecycle_matches_protocol,
    concept_lifecycle_review_signals,
    concept_protocol_ambiguity_state,
    concept_protocol_relevance,
    concept_protocol_relevance_for_source,
    curated_page_template,
    curated_page_transition_profile,
    default_curated_status,
    display_action_status,
    display_curated_status,
    display_judgment_lifecycle_state,
    display_knowledge_lifecycle_state,
    display_protocol_relevance_ambiguity,
    display_protocol_relevance_mode,
    display_rewrite_proposal_status,
    evaluate_page_aging,
    frontmatter_string_list,
    judgment_asset_frontmatter,
    judgment_lifecycle_profile,
    knowledge_lifecycle_active_corpus_ids,
    knowledge_lifecycle_classification,
    knowledge_lifecycle_counts,
    knowledge_lifecycle_governance_summary,
    knowledge_lifecycle_invalidation_signals,
    page_needs_review,
    protocol_related_concept_lifecycle_summary,
    refresh_knowledge_lifecycle_state,
    render_knowledge_lifecycle_entry_summary,
    review_queue,
    rewrite_proposal_needs_review,
    rewrite_proposal_status_rank,
    rewrite_transition_profile,
    select_knowledge_lifecycle_entries,
    sort_curated_pages,
    sort_knowledge_lifecycle_entries,
    transition_profile,
    valid_curated_statuses,
)
from .app_render import (  # noqa: E402
    append_wiki_log,
    build_domain_pilot_scorecard,
    build_domain_pilots,
    build_domain_pilots_incremental,
    build_output_pack_decision_memos,
    build_output_pack_review_packs,
    build_output_pack_sop_drafts,
    build_output_packs,
    build_output_packs_incremental,
    compact_section_lines,
    decision_memo_path,
    decision_memo_recommendation_lines,
    decision_memo_section_lines,
    decision_memos_dir,
    domain_pilot_protocol_input_signature,
    domain_pilot_protocol_inputs,
    domain_pilot_scorecard_is_reusable,
    domain_pilot_state_scorecard,
    domain_pilots_index_path,
    ensure_wiki_log,
    execution_bundle_path,
    execution_bundles_dir,
    execution_proposal_path,
    execution_proposals_dir,
    execution_receipt_path,
    execution_receipts_dir,
    extract_sop_pattern_frequencies,
    furnace_quick_commands,
    judgment_asset_attention_sort_key,
    judgment_asset_gap_codes,
    judgment_asset_shell_record,
    judgment_asset_summary,
    load_workspace_markdown,
    output_pack_decision_memo_group_input_signature,
    output_pack_group_is_reusable,
    output_pack_lifecycle_summary_input_signature,
    output_pack_repair_plan_candidates,
    output_pack_review_candidates,
    output_pack_review_group_input_signature,
    output_pack_reviewed_candidates,
    output_pack_sop_group_input_signature,
    output_pack_state_records,
    output_pack_version_history_lines,
    pack_stem,
    pack_workspace_link,
    pilot_scorecard_path,
    pilot_scorecards_dir,
    pilot_stage,
    protocol_execution_receipts,
    protocol_output_pack_rows,
    protocol_scorecard,
    remove_stale_generated_concept_pages,
    remove_stale_generated_concept_pages_detailed,
    render_agent_pack,
    render_agent_workbench,
    render_aging_report,
    render_cognitive_history,
    render_compile_status,
    render_curated_index,
    render_curated_page_summary,
    render_domain_pilots_index,
    render_furnace_center,
    render_furnace_center_html,
    render_judgment_assets,
    render_master_index,
    render_output_packs_index,
    render_review_center_html,
    render_review_queue,
    review_pack_path,
    review_packs_dir,
    sop_draft_path,
    sop_drafts_dir,
    sop_pattern_key,
    workspace_file_signature,
    workspace_link,
)
