"""Compile output step owner."""

from __future__ import annotations

import logging
from pathlib import Path

from ..app_compile_ops import build_agent_packs
from ..app_shell import build_shell_summary, write_shell_summary
from ..app_state import (
    agent_workbench_path,
    aging_report_path,
    cognitive_history_path,
    concept_quality_path,
    concept_rewrite_index_path,
    default_output_pack_build_state,
    execution_audit_html_path,
    execution_center_html_path,
    furnace_center_html_path,
    graph_health_report_path,
    machine_memory_drift_report_path,
    review_center_html_path,
)
from ..content.io import (
    collect_output_density_artifacts,
    collect_recent_output_artifacts,
)
from ..memory.execution_surfaces import (
    render_concept_quality,
    render_concept_rewrite_index,
    render_concept_rewrite_proposal_page,
    render_execution_audit_html,
    render_execution_center_html,
)
from ..memory.status import (
    render_drift_report,
    render_graph_health,
)
from ..render.cognitive_history import render_cognitive_history
from ..render.furnace_center import render_furnace_center, render_furnace_center_html
from ..render.paths import decision_memos_dir
from ..render.review_center import render_review_center_html
from ..render.views import (
    render_agent_workbench,
    render_aging_report,
    render_review_queue,
)
from .context import CompileContext

logger = logging.getLogger(__name__)


def _stable_output_created_at(path: Path, fallback: str) -> str:
    from ..app_utils import parse_frontmatter

    if not path.exists():
        return fallback
    frontmatter = parse_frontmatter(path.read_text(encoding="utf-8", errors="replace"))
    existing = str(frontmatter.get("created_at") or "").strip()
    return existing or fallback


def _render_auto_figure_artifact(
    *,
    artifact_id: str,
    title: str,
    query: str,
    protocol: str,
    created_at: str,
    generated_at: str,
    body_lines: list[str],
) -> str:
    from ..app_utils import render_frontmatter

    return "\n".join(
        [
            render_frontmatter(
                {
                    "id": artifact_id,
                    "kind": "output",
                    "format": "figure",
                    "query": query,
                    "protocol": protocol,
                    "generated_by": "aiwiki-compile",
                    "created_at": created_at,
                    "generated_at": generated_at,
                    "title": title,
                }
            ),
            "",
            f"# {title}",
            "",
            *body_lines,
            "",
        ]
    )


def _render_auto_slides_artifact(
    *,
    title: str,
    query: str,
    protocol: str,
    created_at: str,
    generated_at: str,
    slides: list[list[str]],
) -> str:
    from ..app_utils import render_scalar

    lines = [
        "---",
        "marp: true",
        'kind: "output"',
        'format: "slides"',
        f"query: {render_scalar(query)}",
        f'protocol: "{protocol}"',
        'generated_by: "aiwiki-compile"',
        f'created_at: "{created_at}"',
        f'generated_at: "{generated_at}"',
        f"title: {render_scalar(title)}",
        "---",
        "",
    ]
    for index, slide in enumerate(slides):
        if index:
            lines.extend(["---", ""])
        lines.extend(slide)
        lines.append("")
    return "\n".join(lines)


def _write_autogenerated_output_artifacts(context: CompileContext) -> None:
    from ..app_utils import slugify

    protocol = context.protocol_state["active_protocol"]
    pages = context.decision_pages + context.judgment_pages
    overdue_pages = [page for page in pages if page.get("overdue_review") == "true"]
    escalated_pages = [page for page in pages if page.get("escalation_candidate") == "true"]
    pending_pages = [page for page in pages if page.get("pending_review") == "true"]
    judgment_relation_edges = list(context.memory.get("edges", {}).get("judgment_to_judgment", []))
    decision_relation_edges = list(context.memory.get("edges", {}).get("judgment_to_decision", []))
    node_map = {
        str(node.get("page_id") or ""): node
        for node in context.memory.get("judgment_nodes", [])
        if isinstance(node, dict) and node.get("page_id")
    }
    relation_figure_path = context.root / "output" / "figures" / "judgment-relation-map.md"
    governance_figure_path = context.root / "output" / "figures" / "governance-health-dashboard.md"
    status_slides_path = context.root / "output" / "slides" / "furnace-governance-status.md"
    density_slides_path = context.root / "output" / "slides" / "furnace-output-density.md"
    decision_memo_count = len(list(decision_memos_dir(context.root).glob("*.md")))
    report_count = len(list((context.root / "output" / "reports").glob("*.md")))
    current_slide_count = len(list((context.root / "output" / "slides").glob("*.md")))
    current_figure_count = len(list((context.root / "output" / "figures").glob("*.md")))
    target_slide_count = current_slide_count + sum(1 for path in (status_slides_path, density_slides_path) if not path.exists())
    target_figure_count = current_figure_count + sum(
        1 for path in (relation_figure_path, governance_figure_path) if not path.exists()
    )

    relation_mermaid: list[str] = ["## Mermaid", "```mermaid", "graph LR"]
    relation_node_lines: list[str] = []
    relation_edge_lines: list[str] = []
    seen_nodes: set[str] = set()
    for edge in (judgment_relation_edges + decision_relation_edges)[:8]:
        left_id = str(edge.get("from") or "")
        right_id = str(edge.get("to") or "")
        relation = str(edge.get("relation") or "related")
        left_node = node_map.get(left_id, {})
        right_node = node_map.get(right_id, {})
        left_key = f"node_{slugify(left_id).replace('-', '_')}"
        right_key = f"node_{slugify(right_id).replace('-', '_')}"
        if left_key not in seen_nodes:
            seen_nodes.add(left_key)
            left_label = str(left_node.get("title") or left_id).replace('"', "'")
            relation_node_lines.append(f'    {left_key}["{left_label}"]')
        if right_key not in seen_nodes:
            seen_nodes.add(right_key)
            right_label = str(right_node.get("title") or right_id).replace('"', "'")
            relation_node_lines.append(f'    {right_key}["{right_label}"]')
        if relation == "supports":
            connector = "-->"
        elif relation == "contradicts":
            connector = "-.->"
        else:
            connector = "---"
        relation_edge_lines.append(f"    {left_key} {connector}|{relation}| {right_key}")
    if not relation_node_lines:
        relation_mermaid.append('    placeholder["No explicit judgment relations yet"]')
    else:
        relation_mermaid.extend(relation_node_lines)
        relation_mermaid.extend(relation_edge_lines)
    relation_mermaid.append("```")

    relation_figure_created_at = _stable_output_created_at(relation_figure_path, context.compiled_at)
    context.write_output_pack_artifact(
        relation_figure_path,
        _render_auto_figure_artifact(
            artifact_id="auto-figure-judgment-relation-map",
            title="Judgment Relation Map",
            query="Auto figure · judgment relation map",
            protocol=protocol,
            created_at=relation_figure_created_at,
            generated_at=context.compiled_at,
            body_lines=[
                "## Summary",
                f"- Judgment relation edges: `{len(judgment_relation_edges)}`",
                f"- Judgment-decision edges: `{len(decision_relation_edges)}`",
                f"- Reviewed judgment assets: `{len(context.memory.get('judgment_nodes', []))}`",
                "",
                *relation_mermaid,
            ],
        ),
    )

    governance_figure_created_at = _stable_output_created_at(governance_figure_path, context.compiled_at)
    context.write_output_pack_artifact(
        governance_figure_path,
        _render_auto_figure_artifact(
            artifact_id="auto-figure-governance-health-dashboard",
            title="Governance Health Dashboard",
            query="Auto figure · governance health dashboard",
            protocol=protocol,
            created_at=governance_figure_created_at,
            generated_at=context.compiled_at,
            body_lines=[
                "## Health Snapshot",
                "| Metric | Value |",
                "| --- | --- |",
                f"| Pending review | `{len(pending_pages)}` |",
                f"| Overdue review | `{len(overdue_pages)}` |",
                f"| Escalation candidates | `{len(escalated_pages)}` |",
                f"| Drift warnings | `{len(context.previous_compile_state.get('drift_warnings', []))}` |",
                "",
                "## Mermaid",
                "```mermaid",
                "flowchart LR",
                f'    pending["Pending {len(pending_pages)}"] --> overdue["Overdue {len(overdue_pages)}"]',
                f'    overdue --> escalated["Escalated {len(escalated_pages)}"]',
                f'    escalated --> relations["Relations {len(judgment_relation_edges) + len(decision_relation_edges)}"]',
                "```",
            ],
        ),
    )

    status_slides_created_at = _stable_output_created_at(status_slides_path, context.compiled_at)
    context.write_output_pack_artifact(
        status_slides_path,
        _render_auto_slides_artifact(
            title="Furnace Governance Status",
            query="Auto slides · furnace governance status",
            protocol=protocol,
            created_at=status_slides_created_at,
            generated_at=context.compiled_at,
            slides=[
                [
                    "# Furnace Governance Status",
                    "",
                    f"- Protocol: `{protocol}`",
                    f"- Pending review: `{len(pending_pages)}`",
                    f"- Overdue review: `{len(overdue_pages)}`",
                    f"- Escalation candidates: `{len(escalated_pages)}`",
                ],
                [
                    "## Judgment Relation Coverage",
                    "",
                    f"- Judgment relation edges: `{len(judgment_relation_edges)}`",
                    f"- Judgment-decision edges: `{len(decision_relation_edges)}`",
                    f"- Judgment assets: `{len(context.memory.get('judgment_nodes', []))}`",
                ],
                [
                    "## Next Moves",
                    "",
                    "- Review overdue pages first.",
                    "- Keep decision pages tied to judgment pages.",
                    "- Use execution/review receipts to close escalations.",
                ],
            ],
        ),
    )

    density_slides_created_at = _stable_output_created_at(density_slides_path, context.compiled_at)
    context.write_output_pack_artifact(
        density_slides_path,
        _render_auto_slides_artifact(
            title="Furnace Output Density",
            query="Auto slides · furnace output density",
            protocol=protocol,
            created_at=density_slides_created_at,
            generated_at=context.compiled_at,
            slides=[
                [
                    "# Furnace Output Density",
                    "",
                    f"- Reports: `{report_count}`",
                    f"- Decision memos: `{decision_memo_count}`",
                    f"- Slides: `{target_slide_count}`",
                    f"- Figures: `{target_figure_count}`",
                ],
                [
                    "## Runtime Coverage",
                    "",
                    f"- Source nodes: `{len(context.memory.get('source_nodes', []))}`",
                    f"- Concept nodes: `{len(context.memory.get('concept_nodes', []))}`",
                    f"- Judgment nodes: `{len(context.memory.get('judgment_nodes', []))}`",
                ],
                [
                    "## Output Focus",
                    "",
                    "- Keep slides tied to runtime state and review backlog.",
                    "- Keep figures tied to machine-memory structure and governance pressure.",
                    "- Let decision memos stay protocol-specific.",
                ],
            ],
        ),
    )


def compile_output_phase(context: CompileContext) -> None:
    _write_autogenerated_output_artifacts(context)
    context.all_outputs = collect_output_density_artifacts(context.root)
    context.recent_outputs = collect_recent_output_artifacts(context.root)

    context.output_packs = default_output_pack_build_state()
    context.dirty_output_pack_groups = []
    context.clean_output_pack_groups = []

    context.domain_pilots = {
        "compiled_at": context.compiled_at,
        "active_protocol": context.protocol_state["active_protocol"],
        "scorecards": [],
    }
    context.dirty_domain_pilot_protocols = []
    context.clean_domain_pilot_protocols = []

    agent_packs = build_agent_packs(
        context.root,
        context.entries,
        context.decision_pages,
        context.judgment_pages,
        context.memory,
        context.protocol_state,
        context.recent_outputs,
        context.compiled_at,
        knowledge_lifecycle=context.knowledge_lifecycle,
    )
    context.write_index_artifact(
        agent_workbench_path(context.root),
        render_agent_workbench(
            agent_packs,
            context.compiled_at,
            context.protocol_state["active_protocol"],
            knowledge_lifecycle=context.knowledge_lifecycle,
        ),
    )
    for pack in agent_packs:
        context.write_index_artifact(context.root / pack["path"], pack["content"])
    context.write_index_artifact(
        context.root / "wiki" / "indexes" / "furnace-center.md",
        render_furnace_center(
            context.decision_pages,
            context.judgment_pages,
            context.memory,
            context.compiled_at,
            context.protocol_state,
            context.recent_outputs,
            context.output_packs,
            context.domain_pilots,
            context.execution_audit,
            knowledge_lifecycle=context.knowledge_lifecycle,
        ),
    )
    context.write_index_artifact(
        review_center_html_path(context.root),
        render_review_center_html(
            context.decision_pages,
            context.judgment_pages,
            context.memory,
            context.compiled_at,
            active_protocol=context.protocol_state["active_protocol"],
            knowledge_lifecycle=context.knowledge_lifecycle,
        ),
    )
    context.write_index_artifact(
        furnace_center_html_path(context.root),
        render_furnace_center_html(
            context.decision_pages,
            context.judgment_pages,
            context.memory,
            context.compiled_at,
            context.protocol_state,
            context.recent_outputs,
            context.output_packs,
            context.domain_pilots,
            context.execution_audit,
            knowledge_lifecycle=context.knowledge_lifecycle,
        ),
    )
    context.write_index_artifact(
        execution_center_html_path(context.root),
        render_execution_center_html(
            context.root,
            context.memory,
            compiled_at=context.compiled_at,
            active_protocol=context.protocol_state["active_protocol"],
        ),
    )
    context.write_index_artifact(
        execution_audit_html_path(context.root),
        render_execution_audit_html(context.execution_audit),
    )
    context.write_index_artifact(concept_quality_path(context.root), render_concept_quality(context.memory))
    context.write_index_artifact(
        concept_rewrite_index_path(context.root),
        render_concept_rewrite_index(context.memory["health"]["concept_rewrite"], context.compiled_at),
    )
    for proposal in context.memory["health"]["concept_rewrite"].get("all_proposals", []):
        context.write_index_artifact(
            context.root / proposal["proposal_path"],
            render_concept_rewrite_proposal_page(proposal),
        )
    context.write_index_artifact(graph_health_report_path(context.root), render_graph_health(context.memory))
    context.write_index_artifact(
        machine_memory_drift_report_path(context.root),
        render_drift_report(context.memory, context.transition),
    )
    context.write_index_artifact(
        context.root / "wiki" / "indexes" / "review-queue.md",
        render_review_queue(
            context.decision_pages,
            context.judgment_pages,
            context.compiled_at,
            active_protocol=context.protocol_state["active_protocol"],
            knowledge_lifecycle=context.knowledge_lifecycle,
            counter_evidence_scan=context.memory.get("health", {}).get("counter_evidence_scan", {}),
        ),
    )
    context.write_index_artifact(
        cognitive_history_path(context.root),
        render_cognitive_history(
            context.root,
            context.decision_pages,
            context.judgment_pages,
            context.compiled_at,
            active_protocol=context.protocol_state["active_protocol"],
            knowledge_lifecycle=context.knowledge_lifecycle,
        ),
    )
    context.write_index_artifact(
        aging_report_path(context.root),
        render_aging_report(
            context.decision_pages,
            context.judgment_pages,
            context.compiled_at,
            active_protocol=context.protocol_state["active_protocol"],
            knowledge_lifecycle=context.knowledge_lifecycle,
        ),
    )
    write_shell_summary(context.root, build_shell_summary(context.root, generated_at=context.compiled_at))


__all__ = ["compile_output_phase"]
